### ISSUE TITLE
Clarify supported languages

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/buildpacks#100]
The README has long lists of languages with options, such as https://github.com/GoogleCloudPlatform/buildpacks#language-idiomatic-configuration-options which includes PHP. This led me to think PHP was supported.

Expected: Languages supported are clearly listed, languages that are in progress are not prominently featured in the main user README.

**Comment by lukasberger** [comment]
PHP is supported in App Engine and Cloud Functions. If you use those builders with pack, you should be able to configure them as outlined in the section you linked.

For the general builder that's used in pack and Cloud Build, the supported languages are listed here: https://github.com/GoogleCloudPlatform/buildpacks#general-builder-and-buildpacks. Is that what you're looking for?

**Comment by jama22** [comment]
You can now find a full list of supported language runtimes https://cloud.google.com/docs/buildpacks/overview
