### ISSUE TITLE
Could either $GOROOT be made available or the go executable be in $PATH

### ISSUE THREAD

**Issue by opinijm** [GoogleCloudPlatform/buildpacks#101]
I'm trying to deploy a go application without a docker file for the default behavior specified. It's set up so that the actual main is run indirectly to give the container a chance to generate some proto code first during deployment. However this indirect run fails because it can't find the go executable. I would love to be able to do this without messing with the GCP configs or download an entirely new dist but I understand that's an avenue I can take. Oh this is on Google Cloud Run

**Comment by opinijm** [comment]
I ended up just adding the common go paths to $PATH ¯\_(ツ)_/¯ Closing this as I know you folks are probably busy doing other things!

**Comment by ndabAP** [comment]
In my `Dockerfile` I needed to add:

```Dockerfile
RUN export PATH=$PATH:/usr/local/go/bin
```
