### ISSUE TITLE
Java Functions Framework Fails with `mvnw`

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/buildpacks#119]
```
=== Java - Maven (google.java.maven@0.9.0) ===
--------------------------------------------------------------------------------
Running "./mvnw clean package --batch-mode -DskipTests --quiet"
Done "./mvnw clean package --batch-mode -DskipTests --quiet" (11.33843831s)
=== Java - Functions Framework Invoker (google.java.functions-framework@1.0.1) ===
--------------------------------------------------------------------------------
Running "mvn --batch-mode dependency:copy-dependencies"
Done "mvn --batch-mode dependency:copy-dependencies" (676.682µs)
Failure: (ID: fce8c4c5) executing command "mvn --batch-mode dependency:copy-dependencies": exec: "mvn": executable file
 not found in $PATH
```

It used `mvnw` correctly, but then fails when it tries to use `mvn`.

Reproducible project: https://github.com/GoogleCloudPlatform/buildpack-samples/tree/functions-framework-java-mvnw/sample-functions-framework-java-mvn

**Comment by matthewrobertson** [comment]
I can look into this.

**Comment by matthewrobertson** [comment]
It looks like [this is the issue](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/java/functions_framework/main.go#L117). We should check if `./mvnw` exists that same as [we do in java/maven/main.go](https://github.com/GoogleCloudPlatform/buildpacks/blob/10f6e4f050380c3a16bfdebcd601876b97373fde/cmd/java/maven/main.go#L77:L78)
