### ISSUE TITLE
ERROR: failed to detect: no buildpacks participating for Nodejs apps

### ISSUE THREAD

**Issue by tummalah** [GoogleCloudPlatform/buildpacks#123]
Hi,
I am trying to run a nodejs build but seems the builder does not recognize the app. I am able to see that package.json exists in the path.

ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 100

**Comment by jamesward** [comment]
Can you run `pack -v ...` to get more details and share them here?  Also have you tried this on the node sample: https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-node

**Comment by tummalah** [comment]
@jamesward This got resolved after updating pack. Thanks so much!!
