### ISSUE TITLE
Is it possible to resolve symlinks during the builder image's `COPY`ing of the source code?

### ISSUE THREAD

**Issue by vinayluzrao** [GoogleCloudPlatform/buildpacks#127]
My source code directory has a symlink that points to a path not contained in its subtree. This is because I have a monorepo, and I share code between projects with symlinks. Therefore, when I try building, the symlink becomes dead (dangling) after being copied into the builder.

A solution that would work is to resolve the symlink as the builder image's `COPY`ing of my source code happens; is this possible?

**Comment by lukasberger** [comment]
I believe `pack` volumes are just Docker volumes under the hood and IIRC Docker volumes don't support symlinks. (I assume you're using pack based on the other issue you filed.)

The repo for the pack tool is https://github.com/buildpacks/pack, please open an issue in that repo for feedback from the maintainers.
