### ISSUE TITLE
Whether the buildpacks-builder should support alternative download urls for program resources?

### ISSUE THREAD

**Issue by tpiperatgod** [GoogleCloudPlatform/buildpacks#128]
When I build go language function the following steps will do access to internet and downloading resources from it:
1. download the go language program from ```goURL``` in ```runtime``` buildpack
2. query and download go dependency packages with ```goproxy``` environment(go version >= 1.15)(can be found in ```functions_framework``` and ```build``` buildpacks)

I cannot build function image while my network connection cannot access the above address.

Is it possible to provide an configuration to select the alternate solution to work in case of poor network conditions? Especially if I have better cdn resources, or if I have a local repository (bucket, e.g.)

Other languages may have the same problem.

**Comment by briandealwis** [comment]
The CNCF project is defining [_assets_](https://github.com/buildpacks/rfcs/blob/main/text/0073-offline-buildpackages.md) which would provide this ability.

**Comment by tpiperatgod** [comment]
I'll look into the `offline-buildpackages`, that's a good idea, thanks!
