### ISSUE TITLE
Python project mistaken as a dotnet project

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/buildpacks#144]
We received a report of a user's python project being detected as a dotnet project.  They were developing a python project using `venv`.  Their `requirements.txt` included `ptvsd` (required for debugging with VSCode).  `ptvsd` causes the following .dlls to be installed (regardless of platform):
```console
$ find . -name '*.dll'
./lib/python3.9/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_amd64.dll
./lib/python3.9/site-packages/ptvsd/_vendored/pydevd/pydevd_attach_to_process/attach_x86.dll
```

And our detectors are finding the `.dll`.
https://github.com/GoogleCloudPlatform/buildpacks/blob/e962ff0ffb981a1fc439ed326f24e4bef80ec65c/cmd/dotnet/runtime/main.go#L56

**Comment by spew** [comment]
This should is fixed by https://github.com/GoogleCloudPlatform/buildpacks/commit/876a88f42652302fe58a6f89bdde8e7e41edafc6
