### ISSUE TITLE
Incorrect error logging by Go functions-framework buildpack

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/buildpacks#147]
The logging we added in https://github.com/GoogleCloudPlatform/buildpacks/commit/e3b1fbb25249e3b158500f787c45d75ebeb3e562 instructing developers to add a blank import for the functions-framework is incorrect. The import should be:

```golang
import (
	_ "github.com/GoogleCloudPlatform/functions-framework-go/funcframework"
)
```

(currently the `/funcframework` suffix is missing)

See GoogleCloudPlatform/functions-framework-go/issues/78 for more information.

**Comment by grant** [comment]
Error messaged fixed with https://github.com/GoogleCloudPlatform/buildpacks/commit/537dc1f9157477db4725ab16e26c78e6f7ab72c8
