### ISSUE TITLE
Don't run scripts when generating a package-lock.json

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/buildpacks#152]
Currently the npm buildpack has [logic](https://github.com/GoogleCloudPlatform/buildpacks/blob/924482b9e208ed869a248767d65dc3c9da00c018/pkg/nodejs/npm.go#L29-L40) to run `npm install --package-lock-only --quiet` in order to generate a `package-lock.json` file in projects that don't include one. This command will cause the [NPM preinstall / postinstall lifecycle hooks to run](https://docs.npmjs.com/cli/v7/using-npm/scripts), which has a couple problems:

1. the hooks will be run twice because we run a `npm ci` later in the build process
2. the hooks will not be use `npx` commands that rely on the automatic installation of dependencies (the `package-lock-only` flag).

There are two options to fix this:

1. don't run the lifecycle hooks when generating the package-lock: `npm install --package-lock-only --quiet --ignore-scripts`
2. skip the package-lock generation all together and use `npm install` to download dependencies

**Comment by briandealwis** [comment]
Do we need to generate a `package-lock.json`?
