### ISSUE TITLE
 failed to create builder: fetch lifecycle: downloading lifecycle connect time out

### ISSUE THREAD

**Issue by uchenxy** [GoogleCloudPlatform/buildpacks#153]
Get "https://github.com/buildpacks/lifecycle/releases/download/v0.11.1/lifecycle-v0.11.1+linux.x86-64.tgz" time out，
how to changet the lifecycle download url?

**Comment by briandealwis** [comment]
I'm guessing you're encountering this running `pack`?  That location is [hard-coded into `pack`](https://github.com/buildpacks/pack/blob/3e1f522e822242f4e66a740e4b884f7b9997b438/pkg/client/create_builder.go#L266-L272).  `pack` only downloads the `lifecycle` for an untrusted builder: for trusted builders, pack will use the `lifecycle` binary that's packaged into the builder image.

**Comment by uchenxy** [comment]
> ~I'm guessing you're encountering this running `pack`? That location is [hard-coded into `pack`](https://github.com/buildpacks/pack/blob/3e1f522e822242f4e66a740e4b884f7b9997b438/pkg/client/create_builder.go#L266-L272). `pack` only downloads the `lifecycle` for an untrusted builder: for trusted builders, pack will use the `lifecycle` binary that's packaged into the builder image.~
> 
> My apologies, on re-reading I see that you are encountering this failure when the build is using `pack` to build the builder:
> 
> https://github.com/GoogleCloudPlatform/buildpacks/blob/68371d735f3ca5fdb3408d5e06cd29631c8a4b83/tools/create-builder.sh#L41
> 
> `pack create-builder` doesn't give an option for overriding the location of the lifecycle. But you can specify a [`uri` element](https://buildpacks.io/docs/reference/config/builder-config/#lifecycle-_optional_) in the `builder.toml` files, such as in the `gcp/base/builder.toml`:
> 
> https://github.com/GoogleCloudPlatform/buildpacks/blob/68371d735f3ca5fdb3408d5e06cd29631c8a4b83/builders/gcp/base/builder.toml#L380-L381
> 
> The lifecycle is only 5MB or so, so unless you're running from a restricted machine then failing to download would indicate some networking configuration error.

Thank you very much for your suggestion, which solved my problem
![image](https://user-images.githubusercontent.com/40748300/140249155-ab6f4e80-1026-499f-86af-946ff6297ae3.png)
