### ISSUE TITLE
Gradle buildpack fails with `error: invalid source release: 17`

### ISSUE THREAD

**Issue by lypht** [GoogleCloudPlatform/buildpacks#155]
Even with `targetCompatibility=17` builds are failing for java17.

```Step #0 - "Buildpack": FAILURE: Build failed with an exception.
Step #0 - "Buildpack": 
Step #0 - "Buildpack": * What went wrong:
Step #0 - "Buildpack": Execution failed for task ':compileJava'.
Step #0 - "Buildpack": > error: invalid source release: 17```

Any assistance would be appreciated.  Thank you!

**Comment by jamesward** [comment]
I haven't tried yet but have you tried to set the `GOOGLE_RUNTIME_VERSION` to `17`?

**Comment by lypht** [comment]
I'm assuming that is a build parameter.  Unfortunately, setting `_GOOGLE_RUNTIME_VERSION` to `17` still failed.  Thank you for the quick response, but still seeking resolution.

**Comment by jamesward** [comment]
Are you using `pack` or something else to run the build?

**Comment by fatorija** [comment]
We are trying to run a spring-boot app using `gradlew` with the following command to generate a docker image
When we execute this we get the error that @lypht mentioned

`./gradlew bootBuildImage` 

This will run Jib under the hood I think.

**Comment by jamesward** [comment]
That does not use Jib. Have you told Spring Boot to use the Google Cloud Buildpacks? If not, it is using the Packeto Buildpacks (the default).

**Comment by fatorija** [comment]
@jamesward thanks for the quick response. You are right, it's using Packeto. I took a look here https://github.com/GoogleCloudPlatform/buildpacks and seems it only supports JVM 8 and 11.

**Comment by jamesward** [comment]
Do you want to stick with the Paketo Buildpacks?  I'd think they support Java 17.  I did test the Google Cloud Buildpacks and they do support JDK 17:
```
pack build --builder=gcr.io/buildpacks/builder -eGOOGLE_RUNTIME_VERSION=17 sample-java-gradle
```

If you want to switch to the Google Cloud Buildpacks, let me know and I can help with that.

**Comment by fatorija** [comment]
@jamesward  thank you for your support and responses. I was able to use the gcp builder locally and build the container without problems. The branch we were working on was throwing that error (I reproduced it locally also) but when I changed to another branch it working as expected.

**Comment by briandealwis** [comment]
Closing as this doesn't seem to be an error with the GCP Buildpacks.
