### ISSUE TITLE
Convert line endings in the mvnw

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/buildpacks#156]
We have a received a number of bug reports from developers struggling to build apps using the maven wrapper:

https://github.com/GoogleCloudPlatform/buildpacks/issues/149
https://github.com/GoogleCloudPlatform/buildpacks/issues/58

After snooping around at other buildpack implementations I suspect there is problem with the wrapper is using Windows' line endings`<cr><lf>` instead of unix style <lf>`. We should be able to fix this using a find and replace on the mvnwrapper before we invoke it in the [maven buildpack](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/java/maven/main.go#L57)

**Comment by aserputov** [comment]
Hey, @matthewrobertson, I would like to work on this issue. Could you please assign it to me?

**Comment by matthewrobertson** [comment]
This was fixed with https://github.com/GoogleCloudPlatform/buildpacks/commit/2f2feac0ab2edc2b3fb05bdd4868aa9603cc24c3

**Comment by matthewrobertson** [comment]
@aserputov sorry we had already assigned this issue to an internal owner. I believe the same issue exists for the gradle wrapper if you want to take a crack at that.

**Comment by aserputov** [comment]
@matthewrobertson no problems, thanks
