### ISSUE TITLE
Impossible to figure out how to get other .net versions in use

### ISSUE THREAD

**Issue by Nixarn** [GoogleCloudPlatform/buildpacks#162]
I need the .net 5 framework but it's impossible to get it working. And the documentation is seriously lacking. It says to use GOOGLE_RUNTIME_VERSION. And I've tried "5", "5.0", "5.0.0", "5.0-alpine", "net5", "5net". Nothing works, it just uses this tag to download the right file form 

https://dotnetcli.blob.core.windows.net/dotnet/Sdk/[TAG]/dotnet-sdk-[TAG]-linux-x64.tar.gz

But it's also impossible to browse what's available. Why not list is somewhere?

**Comment by briandealwis** [comment]
Follow the appropriate SDK version page from https://dotnet.microsoft.com/download/dotnet and you should see the available versions.  For example, for .NET 5.0, I ended up at https://dotnet.microsoft.com/download/dotnet/5.0.  There I see the latest version is 5.0.403.  Plugging in that version into `GOOGLE_RUNTIME_VERSION` worked for me.
```
$ pack build --builder gcr.io/buildpacks/builder:v1 -e GOOGLE_RUNTIME_VERSION=5.0.403 my-example
[...]
===> BUILDING
=== .NET - Runtime (google.dotnet.runtime@0.9.1) ===
Using .NET Core SDK version from env: 5.0.403
Installing .NET SDK v5.0.403
--------------------------------------------------------------------------------
Running "bash -c curl --fail --show-error --silent --location --retry 3 https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.403/dotnet-sdk-5.0.403-linux-x64.tar.gz | tar xz --directory /layers/google.dotnet.runtime/runtime --keep-directory-symlink --strip-components=1"
Done "bash -c curl --fail --show-error --silent --location --retry..." (35.30016474s)
=== .NET - Publish (google.dotnet.publish@0.9.0) ===
Installing application dependencies.
--------------------------------------------------------------------------------
Running "dotnet restore --packages /layers/google.dotnet.publish/packages ./helloworld.csproj (DOTNET_CLI_TELEMETRY_OPTOUT=true)"

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.403
[...]
```
