### ISSUE TITLE
Where to report security issues?

### ISSUE THREAD

**Issue by fkautz** [GoogleCloudPlatform/buildpacks#168]
I found a possible security issue with the GCP buildpack.

Where should I report it? I'm not comfortable reporting it here in public.

**Comment by matthewrobertson** [comment]
Hi @fkautz. You can email me directly: mattrobertson@google.com. Thank you!

**Comment by jamesward** [comment]
Oh, we do need a SECURITY.md in this repo. I think something like: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/SECURITY.md
