### ISSUE TITLE
Nodejs builds with lifecycle scripts fail because of --production=false flag

### ISSUE THREAD

**Issue by Banttu** [GoogleCloudPlatform/buildpacks#174]
Since [Yarn 2 support](https://github.com/GoogleCloudPlatform/buildpacks/commit/083551c792d7de30f40242d07b93164507a840dd) was added the --production=false flag has been used for installing dependencies. This causes issues with projects that use lifecycle scripts. In my case this new command triggers the typescript compiler and the build fails since no tsconfig is present.

I tried adding NODE_ENV explicitly to the build variables, but it doesn't affect anything (the production flag overrides it).

The simple solution on my end would be just to remove the tsconfig from .gcloudignore, but I since it's specified [here](https://cloud.google.com/functions/docs/writing/specifying-dependencies-nodejs) that the dependencies are installed with the production flag I think it should work without any additional changed on my end.

The current command used to download prod dependencies is:
`yarn install --non-interactive --prefer-offline --production=false --frozen-lockfile`

The old command was this:
`yarn install --non-interactive --frozen-lockfile (NODE_ENV=production)`

My Cloud Functions use Node 16 as the runtime.

**Comment by matthewrobertson** [comment]
Hi @Banttu sorry to hear you are having trouble. Could you share a bit more about your project setup? Specifically how have you configured the scripts in your package.json file? I am a bit confused why `tsc` is being triggered now if it wasn't triggered before.

The change to `--production=false` was intentional to help developers who wanted to run scripts that required devDependencies. Have you considered just compiling the typescript when you deploy the function?

**Comment by Banttu** [comment]
@matthewrobertson 

In this specific project the issue was caused by the `prepublish` script that included a build command. I'm not sure how common this use case actually is. The previous command didn't trigger it. 

I was able to successfully deploy the functions by removing the `prepublish` command entirely, since it wasn't really something was **required** (I'm not really sure why it had ever been added).

We actually compile the code in our Bitbucket pipelines before using `gcloud beta functions deploy`.

**Comment by koistya** [comment]
Here is Yarn-based GCF project setup: https://github.com/kriasoft/relay-starter-kit → `api`

The API Cloud Function is being bundled with Yarn v3.2.0 CLI and NPM packages. Ater you run `yarn api:build`, the build output looks like this:

```
/api/dist
 ├── .yarn/            # Yarn CLI and bundled API packages
 ├──.pnp.cjs           # Yarn's PnP 
 ├──.pnp.loader.mjs    # ESM with PnP support
 ├──.yarnrc.yml        # Yarn configuration (version number, CLI path `.yarn/release/yarn-{version}.js`)
 ├──index.js           # Bundled application code
 ├── package.json             
 └── yarn.lock   
```

Then when your run `yarn api:deploy` it deploys the API package to GCF from the `./api/dist` folder.

**Comment by koistya** [comment]
It seems like `yarn install` no longer uses the correct Yarn version (found in [`.yarnrc.yml`](https://github.com/kriasoft/relay-starter-kit/blob/71462f8c707200b81800c13063147e01799dc6e6/.yarnrc.yml#L23) file).

**Comment by Banttu** [comment]
@koistya

For us the `DEBUG: ***** CACHE MISS: "prod dependencies"` was present before this change.

We're using yarn v1.22.17 so we don't get this operation error you mentioned.

**Comment by matthewrobertson** [comment]
I think this is all working as expected as I think this is an unusual edge case and`prepublish` hooks shouldn't mutate the project source.
