### ISSUE TITLE
COMPOSER_MEMORY_LIMIT on App Engine PHP7 build

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#176]
I'm trying to pass `COMPOSER_MEMORY_LIMIT` to App Engine Standard PHP7 buildback.

According to https://cloud.google.com/appengine/docs/standard/php7/config/appref#build_environment_variables and https://github.com/GoogleCloudPlatform/buildpacks#language-idiomatic-configuration-options I added to my app.yaml:
```
build_env_variables:
  COMPOSER_MEMORY_LIMIT: -1
```

Env is not passed to the build process. Is there something I'm doing wrong or it's a bug?

**Comment by matthewrobertson** [comment]
How are you deploying your app? Build env vars is still a preview feature so you need to use `gcloud beta app delploy`. Sorry for the confusion.

**Comment by sl0wik** [comment]
I deploy the app using regular `gcloud app deploy`. Without the option to set composer variables, most of the apps require extra CI to build a composer lock file.

**Comment by sl0wik** [comment]
It looks like at some point limit was lifted from 512 mb to 1.5G so I cant catch memory errors anymore. I saw this error happening while running build from.

If someone got this issues the solution might be adding to composer.json `scripts` section:
```
        "pre-update-cmd": [
            "@putenv COMPOSER_MEMORY_LIMIT=2G"
        ]
```
