### ISSUE TITLE
Yarn build pack times out for App Engine Standard deploys

### ISSUE THREAD

**Issue by jscott22** [GoogleCloudPlatform/buildpacks#177]
After [this commit](https://github.com/GoogleCloudPlatform/buildpacks/commit/0c08a9c7992b50c941f8be8f49f74ffe12317a24#diff-7f171c37897b2bd5b3bcafe051b07af8bf09746350a61f30a9acf3aef18c0431R78), our nodejs GAE standard environment builds have been timing out due to dev dependencies being installed. The time to install dev dependencies and run the `cp --archive` command is now roughly 6-7 minutes. This is a problem since with App Engine standard environment, the build timeout can't be increased past the default 10 minutes. 

![image](https://user-images.githubusercontent.com/28190937/152491512-ea4f9304-7e32-40cb-8a52-cb1c06a3cdce.png)

It seems as if the process is much slower even when there's a cache hit. Luckily one of our builds finished after 9min36s, but the subsequent build that had a cache hit for node modules had the second `yarn install` command with `--production=true` take 3 minutes with an overall build time of 8m16s. Before these changes, our builds for the same service were taking ~4m.

You can see here that even on a cache hit, the second yarn install fetches the packages again.

![image](https://user-images.githubusercontent.com/28190937/152489181-e2a57ffc-d760-4123-bcf3-dcd54ab2471b.png)

**Comment by matthewrobertson** [comment]
Is it possible to share which dependencies you have listed in your package.json?

**Comment by matthewrobertson** [comment]
We should probably switch using a symlink instead of `cp`ing between the layer and workspace.

**Comment by matthewrobertson** [comment]
Also, there is no reason we should be preventing people from extending the build timeout when deploying to GAE.

**Comment by matthewrobertson** [comment]
https://github.com/GoogleCloudPlatform/buildpacks/commit/63f407527a888b04c4becdf60d7221ad6be40ee6 is the fix for this. It take some time to land in all GCP regions. I will report back here when it is in.

**Comment by matthewrobertson** [comment]
Fix should be deployed for `nodejs16` and `nodejs14` runtimes. Please re-open if you are continuing to have problems.
