### ISSUE TITLE
Container Healthcheck fails unable to load Node.js PnP dependencies

### ISSUE THREAD

**Issue by koistya** [GoogleCloudPlatform/buildpacks#179]
After the recent "buildpack" release, deploying a gen1/gen2 Cloud Function stopped working with the error:

```
ERROR: (gcloud.alpha.functions.deploy) 
  OperationError: code=3,
  message=Could not create or update Cloud Run service api, Container Healthcheck failed.
          Cloud Run error: Container failed to start. Failed to start and then listen on the port defined
          by the PORT environment variable. Logs for this revision might contain more information.
```

```
Detailed stack trace: Error [ERR_MODULE_NOT_FOUND]:
  Cannot find package 'express' imported from /workspace/index.js
```

It looks like it's no longer able to load PnP dependencies during the container healthcheck.

Before that update, it was possible to deploy a Node.js package with PnP dependencies by adding `--set-env-vars=NODE_OPTIONS=--require=./.pnp.cjs` argument to `gcloud functions deploy` command. Right now, it seems like regardless of setting this environment variable or not, the GCF runtime ignores `.pnp.cjs` file during initial the GCF app launch.

#### Temporary Workaround

Change PnP to `node_modules` linker by running `yarn config set nodeLinker node-modules` (e.g. as part of the `build` step inside of the `dist` (`build`) folder before `gcloud functions deploy` it to GCF.

**Comment by matthewrobertson** [comment]
In theory this should work without the `--require=./pnp.cjs` now because we updated the Functions Framework buildpack to call `yarn functions-framework` in https://github.com/GoogleCloudPlatform/buildpacks/commit/c5bf000ef66c97ac30671d465b4711d1649115e7.

We do have an acceptance test for this [here](https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/testdata/nodejs/functions/yarn_two_pnp) and it seems to be working.

Do you have `@google-cloud/functions-framework` listed as a dependency in your package.json? It is required in PnP mode because don't install anything that is not in the `.yarn/cache` (although that should fail the build).

**Comment by koistya** [comment]
@matthewrobertson indeed, I didn't have `@google-cloud/functions-framework` dependency listed in `package.json`. Note, though, that it did work OK without this dependency before the recent buildpack update (deployment succeeded and the app was loading dependencies via PnP at runtime).

I'm getting the same `gcloud functions deploy` error now, but a different runtime error (when it's trying to do container healthcheck):

```
"/bin/bash: node_modules/.bin/functions-framework: No such file or directory"
```

**Comment by koistya** [comment]
@matthewrobertson by including `@google-cloud/functions-framework` and setting `NODE_OPTIONS=--require=./.pnp.jcs --require=source-map-support/register` environment variable I'm able now to deploy the app to GCF Gen1, but not to Gen2.

**Comment by koistya** [comment]
@matthewrobertson it seems like deploying a Node.js app with PnP dependencies to GCF Gen2 started working again. There is a healthcheck warning in the console logs though:

`Unknown https://1-dot-45d4e764c8eae213702f39069584d51e-dot-u05aca629a62ddd60p-tp.appspot.com/_ah/healthcheck
The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/functions/docs/troubleshooting#scalability`
