### ISSUE TITLE
Consider making build tools available for "build" and excluded for "launch"

### ISSUE THREAD

**Issue by Manny2014** [GoogleCloudPlatform/buildpacks#181]
In order to output a "lean" image, build tools such as jdk and maven should only be made available to the "build" phase of the lifecycle in the layer content metadata. Keeping these will not only increases the size of the image but also be susceptible to vulnerabilities/CVE's.

Alternatively, expose an environment variable that allows the option to keep around or remove. 

I looked around the docs and didn't see any particular reason to keep these layers around but possible I missed something.

Thanks!

**Comment by spew** [comment]
It is a mistake that those layers are available at launch (unless your build activated devmode).

**Comment by Manny2014** [comment]
So the image I inspected was built via skaffold which make use of devmode. I just inspected one which was not and it is clean. Question, in the case of Cloud Deploy which leverages skaffold, is devmode used?

**Comment by spew** [comment]
Hi @Manny2014 thanks for the reply. That is not a question I have the answer to, can you point me to a quickstart or hello world tutorial that you followed so I can make sure I am testing the same thing you are looking at ?

**Comment by Manny2014** [comment]
@spew no worries, i think your explanation regarding DEVMODE covers what i needed. The Cloud Deploy bit was more of a curiosity but it seems that you trigger the image build via cloud build, so you are not bound to the skaffold.yaml. 

Thanks again for the help!

**Comment by spew** [comment]
Thanks, closing, feel free to open another issue for anything new you find.
