### ISSUE TITLE
BuildPack NodeJS 18.0.0 Fails /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by dweekly** [GoogleCloudPlatform/buildpacks#198]
Example of failed build:
https://console.cloud.google.com/cloud-build/builds/b211a24b-b936-4127-8e02-3f606069f241

note that package.json includes
  "engines": {
    "node": ">= 12.0.0"
  },

Logs:

Step #0 - "Buildpack": ===> BUILDING
Step #0 - "Buildpack": === Node.js - Runtime (google.nodejs.runtime@0.9.2) ===
Step #0 - "Buildpack": Resolving Node.js version based on semver ">= 12.0.0"
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Running "curl --fail --show-error --silent --location --get --data-urlencode range=>= 12.0.0 http://semver.io/node/resolve"
Step #0 - "Buildpack": 18.0.0Done "curl --fail --show-error --silent --location --get --data-ur..." (542.67211ms)
Step #0 - "Buildpack": Using resolved runtime version from package.json: 18.0.0
Step #0 - "Buildpack": Installing Node.js v18.0.0
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Running "bash -c curl --fail --show-error --silent --location --retry 3 https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz | tar xJ --directory /layers/google.nodejs.runtime/node --strip-components=1"
Step #0 - "Buildpack": Done "bash -c curl --fail --show-error --silent --location --retry..." (3.115830453s)
Step #0 - "Buildpack": === Node.js - NPM (google.nodejs.npm@0.9.0) ===
Step #0 - "Buildpack": Failure: (ID: 653c7ba4) node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Sorry your project couldn't be built.
Step #0 - "Buildpack": Our documentation explains ways to configure Buildpacks to better recognise your project:
Step #0 - "Buildpack":  -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
Step #0 - "Buildpack": If you think you've found an issue, please report it:
Step #0 - "Buildpack":  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": ERROR: failed to build: exit status 1
Step #0 - "Buildpack": ERROR: failed to build: executing lifecycle: failed with status code: 51
Finished Step #0 - "Buildpack"
ERROR
ERROR: build step 0 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1

**Comment by fmr683** [comment]
I'm getting the issue.

**Comment by schnucks-bgnelson** [comment]
I am having this issue as well.

**Comment by AjayRaineni** [comment]
i am having the same issue

**Comment by DouglasSalazar** [comment]
i am having the same issue

**Comment by Jonathan-Hofmann** [comment]
Having the same issue... Is there any 'way around'?

**Comment by abes1809** [comment]
My team was able to solve this by specifying the node version in our package.json file like so

```
"engines": {
    "node": "17.1.x"
  },
```
it seems Heroku made an update that attempts to install node version 18 on all apps so it is breaking some that run on older versions.

**Comment by DouglasSalazar** [comment]
The error is occurring because node 18.0.0 requires the installation of lib GLIBC_2.28, if the server has nvm installed it will always download the latest versions. In my case I was using amazon linux that was in version 2.26, I made the change to ubuntu 20.4 and it solved.

**Comment by chech0x** [comment]
I'm getting the issue in Google Cloud Run that uses this build pack. 
In  our case , we **had to fix the engine to a lower version** 

```
  "engines": {
    "node": "= 14.x"
  },
```

**Comment by robvanderleek** [comment]
FWIW, bumped into the same issue, pinning to Node 16.x in `package.json` worked for me:

```
  "engines": {
    "node": "= 16.x"
  },
```

Heroku deployment output:

```
remote: -----> Installing binaries        
remote:        engines.node (package.json):  = 16.x        
remote:        engines.npm (package.json):   unspecified (use default)        
remote:        engines.yarn (package.json):  unspecified (use default)        
remote:                
remote:        Resolving node version = 16.x...        
remote:        Downloading and installing node 16.14.2...        
```

**Comment by matthewrobertson** [comment]
Our base images are based on Ubunut 18. Nodejs18 dropped support for Ubunutu 18 because it doesn't include a new enough version of gcc. We are investigating a few solutions, for now you can pin to nodejs16 in your package.json file, as others have suggested:

```
"engines": {
    "node": "= 16.x"
  },
```

**Comment by makhatemakhate** [comment]
@matthewrobertson 
all of my `package.json` files are in `/usr/lib/node_modules/npm/node_modules/`
When can i find the right file to edit.
***after editing the file what do i do?***

**Comment by matthewrobertson** [comment]
@makhatemakhate you should have one in the root directory of your application source code.

**Comment by kobenauf** [comment]
I gather three things from the comments above:

1) Google (I assume?) needs to add GLIBC_2.28 to the environment so Node 18 runs.
2) Until Google does that, run an older version of Node.
3) Possibly build an image outside of Google and use it.

Are these right?
