### ISSUE TITLE
Failed to create buildpack for Node.js v18.0.0

### ISSUE THREAD

**Issue by dcarnese** [GoogleCloudPlatform/buildpacks#200]
Step #0 - "Buildpack": ===> BUILDING
Step #0 - "Buildpack": === Node.js - Runtime (google.nodejs.runtime@0.9.2) ===
Step #0 - "Buildpack": Resolving Node.js version based on semver ">= 14.0.0"
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Running "curl --fail --show-error --silent --location --get --data-urlencode range=>= 14.0.0 http://semver.io/node/resolve"
Step #0 - "Buildpack": 18.0.0Done "curl --fail --show-error --silent --location --get --data-ur..." (185.5037ms)
Step #0 - "Buildpack": Using resolved runtime version from package.json: 18.0.0
Step #0 - "Buildpack": Installing Node.js v18.0.0
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Running "bash -c curl --fail --show-error --silent --location --retry 3 https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz | tar xJ --directory /layers/google.nodejs.runtime/node --strip-components=1"
Step #0 - "Buildpack": Done "bash -c curl --fail --show-error --silent --location --retry..." (2.783048014s)
Step #0 - "Buildpack": === Node.js - NPM (google.nodejs.npm@0.9.0) ===
Step #0 - "Buildpack": Failure: (ID: 653c7ba4) node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": Sorry your project couldn't be built.
Step #0 - "Buildpack": Our documentation explains ways to configure Buildpacks to better recognise your project:
Step #0 - "Buildpack":  -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
Step #0 - "Buildpack": If you think you've found an issue, please report it:
Step #0 - "Buildpack":  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
Step #0 - "Buildpack": --------------------------------------------------------------------------------
Step #0 - "Buildpack": ERROR: failed to build: exit status 1
Step #0 - "Buildpack": ERROR: failed to build: executing lifecycle: failed with status code: 51
Finished Step #0 - "Buildpack"
ERROR
ERROR: build step 0 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1

**Comment by adamblok** [comment]
I you want to use node v14, use this in your package.json file

```json
"engines": {
  "node": "14"
},
```

Then deploy it again.

**Comment by grant** [comment]
Node 18 isn't active LTS and isn't supported by buildpacks.

The list of versions supported by buildpacks is here:

https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/gcf
