### ISSUE TITLE
Comute engine create with container + SSD

### ISSUE THREAD

**Issue by lappazos** [GoogleCloudPlatform/buildpacks#202]
in the SSD guide https://cloud.google.com/compute/docs/disks/add-local-ssd#gcloud I need to perform some operations in the host to format the SSD. how can I do it if I immediately lunch a container?

**Comment by jama22** [comment]
@lappazos could you please clarify how you're performing the operations? Are you using the CLI? some scripting like terraform? FYI this repo is scoped to issues affecting the GCP buildpacks.

**Comment by jama22** [comment]
Closing since i haven't heard an update. Feel free to open a new issue!
