### ISSUE TITLE
Add support for Artifact Registry in yarn

### ISSUE THREAD

**Issue by yutaroyoshikawa** [GoogleCloudPlatform/buildpacks#205]
I have a web project that uses yarn v1 for package management hosted on Google App Engine.
Newly, I am trying to use private npm packages managed by Artifact Registry in my project.
I believe that buildpacks recognizes the .npmrc when building App Engine and automatically generates an access token if the package manager is npm, but yarn does not support automatic generation of this access token, so I would like you to consider supporting this.

**Comment by AkselAllas** [comment]
I managed to hack it by adding a yarn preinstall hook to `package.json`

```
    "preinstall": "printf \"@SCOPE:registry=https://private.repository/\n//private.repository/:always-auth=true\n\n//private.repository/:_authToken=$(gcloud auth print-access-token)\" > .npmrc; yarn install --ignore-scripts; kill -9 $(ps | grep 'yarn.js install' | awk 'NR==1' | awk '{print $1}')"
```

**Comment by jama22** [comment]
Makes sense. For additional context, it sounds like a request to extend the capabilities of this feature we introduced in App Engine / Cloud Functions (https://cloud.google.com/appengine/docs/standard/nodejs/specifying-dependencies#private_dependencies_with_artifact_registry) that allows users to access their packages hosted in Artifact Registry without performing additional configuration.

I think yarn would be a good next package to pick up to support Node.js workloads

**Comment by savarex** [comment]
+1 for this. Ran into the same problem. heart

**Comment by kritkasahni-google** [comment]
Enabled AR support for yarn1 -> https://github.com/GoogleCloudPlatform/buildpacks/commit/92cbbdebc4f810d757e2dc44fa9599fca9a7936c

**Comment by kritkasahni-google** [comment]
Enabled AR support for yarn2 -> https://github.com/GoogleCloudPlatform/buildpacks/commit/e924f3bfa5ed17e0d755b6df24568e5f6f57eb34

**Comment by jama22** [comment]
For future reference, docs have also been updated on GCP Buildpacks [Node.js page](https://cloud.google.com/docs/buildpacks/nodejs#using_yarn)
