### ISSUE TITLE
Images are shown as created 40 years ago

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#21]
I just did `pack build` and run `docker images | head` as usual to verify my image size.

To my surprise I could not see my image among the first images because it was built 40 years ago:

```
docker images | grep 'gcr.io/ahmetb-demo/sample-node'
gcr.io/ahmetb-demo/sample-node                                          latest                                                             ca6b08efb344        40 years ago        182MB
```

by design or a bug?

**Comment by lukasberger** [comment]
The image creation time is controlled by `pack build`. I believe it is reset intentionally to make builds reproducible. If you think it's a bug, please file an issue against pack at https://github.com/buildpacks/pack/issues.

**Comment by ahmetb** [comment]
Yeah, I was suspecting of reproducibility. It looks like it's set to `1980-01-01T00:00:01Z` which isn't 1970, so assuming intentional.
