### ISSUE TITLE
Unable to find node version 12.11.0

### ISSUE THREAD

**Issue by ShubhaPradeep** [GoogleCloudPlatform/buildpacks#215]
I got the below error during training when I was practicing the lab

WARNING: Failed to download Node.js version 12.11.0. You can specify the verison by setting the GOOGLE_RUNTIME_VERSION environment variable
[builder] Failure: (ID: 58e6a0ae) fetching https://dl.google.com/runtimes/nodejs/nodejs-12.11.0.tar.gz returned HTTP status: 404

**Comment by mxgit1090** [comment]
According to the [test file](https://github.com/GoogleCloudPlatform/buildpacks/blob/d503dd7b83553b2f6a1576e213a21b506a5e5ec8/builders/gcp/base/acceptance/nodejs_test.go#L50)

Add environment variable `GOOGLE_RUNTIME_VERSION` to `14.17.0` as below, and it works

```sh
pack build --builder=gcr.io/buildpacks/builder --env 'GOOGLE_RUNTIME_VERSION=14.17.0' sample-node
```

**Comment by spew** [comment]
Can you help by posting the training / what app you are trying to deploy? I am trying to understand where the version 12.11.0 is coming from.

**Comment by spew** [comment]
Issue here is we need to backfill our versions of nodejs.

**Comment by ShubhaPradeep** [comment]
I don't have access to the lab anymore. It was the cloud run lab assignment.

**Comment by paul-feng-github** [comment]
@ShubhaPradeep Do you have any special reason to use nodejs 12.11.0 but not other versions? This is an old version and there is some issues with the release of 12.11.0 tarball https://github.com/nodejs/node/issues/29709. I suggest use a newer version.

**Comment by ShubhaPradeep** [comment]
I don't have access to lab, I got the error when I attended cloud run training and I was practicing my lab the next day.

**Comment by paul-feng-github** [comment]
Added nodejs 12.11.0, it should be available from now
