### ISSUE TITLE
dotnet build pack sometimes uses the wrong runtimeconfig.json

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/buildpacks#216]
This was reported via [this .NET Functions Framework issue](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/issues/251).

When a .NET build contains multiple projects, using `GOOGLE_BUILDABLE` to specify the "main" one, there's the possibility of multiple runtimeconfig.json files being generated, one for each project. (For example, a dependency project which targets `netcoreapp3.1` and includes a package dependency of `EntityFramework`.)

The [current code](https://github.com/GoogleCloudPlatform/buildpacks/blob/97aaaa42973215873bbcf1a7694d971aa4ecee24/pkg/dotnet/dotnet.go#L323) uses the first one found, whereas it should use the one associated with the "main" project.

There's a repro in the linked issue, or I can create a new one if that's useful.

**Comment by jskeet** [comment]
Wonderful - thanks so much for addressing this. Please let me know if I can help in testing etc.

**Comment by jinglundong** [comment]
I'm adding more debug info to the buildpack. It turned out that we only look at the specified project. I don't know if there's a sticky behavior somewhere, but my all 4 builds picked the correct project. I passed in `--env GOOGLE_BUILDABLE=ServiceSight.FunctionTest` all the time. 

```
pack build sample-dotnet --builder gcp/dotnet --path third_party/gcp_buildpacks/builders/testdata/dotnet/generic/cs_nested_with_dep/ --trust-builder --env GOOGLE_BUILDABLE=ServiceSight.FunctionTest -v

...

=== .NET - Runtime (google.dotnet.runtime@0.9.1) ===
found multiple runtimeconfig.json files
found runtimeconfig.json file: ServiceSight.FunctionTest/bin/Release/netcoreapp3.1/ServiceSight.FunctionTest.runtimeconfig.json

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    }
  }
}
found runtimeconfig.json file: bin/ServiceSight.FunctionTest.runtimeconfig.json

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    }
  }
}
Using runtimeconfig file "ServiceSight.FunctionTest/bin/Release/netcoreapp3.1/ServiceSight.FunctionTest.runtimeconfig.json"
```

I read the [error](https://github.com/GoogleCloudPlatform/functions-framework-dotnet/issues/251#issue-1291187077) again, it's actually complaining a missing key. My assumption (which is used by the current implementation) is that the framework name is always "Microsoft.AspNetCore.App" [code](https://github.com/GoogleCloudPlatform/buildpacks/blob/97aaaa42973215873bbcf1a7694d971aa4ecee24/pkg/dotnet/dotnet.go#L45). The framework in the error is ""Microsoft.NETCore.App"". This issue is probably caused by a wrong assumption. If anyone knows the correct way to select the framework entry, please let me know. Otherwise, I will look into it tomorrow.

**Comment by jinglundong** [comment]
Found some explanation on a blog post [1]. 
```
Microsoft.NETCore.App - the .NET Core framework that previously was the only framework installed
Microsoft.AspNetCore.App - all the dlls from packages that make up the "core" of ASP.NET Core, with as many packages that have third-party dependencies removed
Microsoft.AspNetCore.All - all the packages that were previously referenced by the Microsoft.AspNetCore.All metapackage, including all their dependencies.
```
[1] - https://andrewlock.net/exploring-the-microsoft-aspnetcore-app-shared-framework-in-asp-net-core-2-1-preview-1/

**Comment by AshleyMedway** [comment]
The different SDKs was removed in 3.1. 

If it helps this issue was introduced on 2022/06/30 the example project would have built fine before then.

**Comment by jskeet** [comment]
It's not a matter of finding a different key within the same file - it's about using the right file to start with. We need to be looking at runtimeconfig.json for the project we want to run, instead of for the dependency.

(We also need to select the right entry, but I think we're probably doing that at least reasonably correctly at the moment.)

**Comment by jinglundong** [comment]
I had a repro now. 

```
found multiple runtimeconfig.json files
found runtimeconfig.json file: ServiceSight.Dependancy/bin/Release/netcoreapp3.1/ServiceSight.Dependancy.runtimeconfig.json

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    }
  }
}
found runtimeconfig.json file: ServiceSight.FunctionTest/bin/Release/netcoreapp3.1/ServiceSight.FunctionTest.runtimeconfig.json

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    }
  }
}
found runtimeconfig.json file: bin/ServiceSight.FunctionTest.runtimeconfig.json

{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "3.1.0"
    }
  }
}
```

**Comment by AshleyMedway** [comment]
We are trying to apply the changes required for the workaround, targeting netstandard2.1 but it’s easier said than done, some dependencies are having to be broken apart. 

We are trying but the workaround might take us longer to implement than the fix :/

**Comment by AshleyMedway** [comment]
Yeah we are going to have to give up on the workaround, we just keep coming across more and more issues. It's probably a something we need to address in our codebase long term but short term its not going to be an option for us.

Is there some way we can select a buildpack version with a flag or something?

**Comment by jinglundong** [comment]
I'm still working on the fix. 

Not sure if you tried the other workaround of changing the alphabetical order of ServiceSight.FunctionTest and ServiceSight.Dependancy. We believe ServiceSight.Dependancy's framework version was picked because its alphabetical order is before ServiceSight.FunctionTest. 

There might be another workaround by 'prebuilt' the app before calling gcloud. Please let me know if you need more details or have any problems.

**Comment by AshleyMedway** [comment]
The trouble is you have to rename the folder not just the project, this would mean 10 folder renames and updating all the references etc. it’s a bit of a mess. 

Would love to deploy prebuilt code: https://github.com/GoogleCloudPlatform/buildpacks/issues/113

**Comment by jinglundong** [comment]
Sorry about my previous suggestion about using presbuilt app. It's supported in OSS/Cloud Run use case, but not in GCF. 

https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/dotnet/buildpack.toml#L96

**Comment by jinglundong** [comment]
Sorry, the fix took longer than I expected. New ETA is July 27th.

**Comment by AshleyMedway** [comment]
@jinglundong Are we still on track for the 27th July?

**Comment by jinglundong** [comment]
The worst case is 29th July. We already started the release of the candidate contains the fix. I'm trying to figure out if there's a reliable way to hit the new candidate before it's 100% in prod. 

The new image is: `gcr.io/gae-runtimes/buildpacks/dotnet/builder@sha256:e7c2b46b438fc9170d718158d96188f58b8336018d905e4bcd78cba5ab06d495`. Disclaimer: please don't depend on this image directly or its format for any production usage. I tried to set it via --set-build-env-vars, but I couldn't find any build-env-vars to specify the builder image.

**Comment by AshleyMedway** [comment]
@jinglundong we are still seeing the issue this morning. Is there a timeline for when the new candidate to be 100% available?

**Comment by jinglundong** [comment]
My worst case estimate wasn't taking release pipeline block into the consideration. So, sorry about that. 

Since 10:00 UTC or 03:00 PDT July 28th, our release pipelines have been blocked by a network issue. Roughly 40% of the regions haven't picked up this fix. We released the fix to europe-west3 fully, and europe-west1 partially before the release pipeline was blocked. Unfortunately, some European regions like europe-west2 are still blocked.

**Comment by jinglundong** [comment]
I started an emergency rollout. According to our metrics, > 96% of the dotnet3 deployments are running the new code. I verified it with a deployment `gcloud functions deploy test-function --runtime=dotnet3 --trigger-http --allow-unauthenticated --entry-point=TestFunction.Function --verbosity=debug --set-build-env-vars GOOGLE_BUILDABLE=Function`. I was able to trigger the function via http. 

Please let us know if you are still seeing the problem.

**Comment by EatonZ** [comment]
Hello, it seems the changes made here have broken my build. Can you clarify what changes I need to make in my project to fix it? I am using the pack CLI on Windows. Log:

```
v1: Pulling from buildpacks/builder
Digest: sha256:52bcf24f85753c85b133642f51675078ab5b0402cf0cc4b40ab4f503163075d4
Status: Image is up to date for gcr.io/buildpacks/builder:v1
===> ANALYZING
===> DETECTING
4 of 6 buildpacks participating
google.dotnet.sdk     0.9.1
google.dotnet.publish 0.9.0
google.dotnet.runtime 0.9.1
google.utils.label    0.0.2
===> RESTORING
Restoring metadata for "google.dotnet.publish:packages" from cache
Restoring metadata for "google.dotnet.runtime:runtime" from app image
Restoring metadata for "google.dotnet.runtime:sdk" from cache
Restoring data for "google.dotnet.publish:packages" from cache
Restoring data for "google.dotnet.runtime:runtime" from cache
Restoring data for "google.dotnet.runtime:sdk" from cache
===> BUILDING
=== .NET - SDK (google.dotnet.sdk@0.9.1) ===
Looking for global.json in /workspace
2022/08/09 20:57:05 [DEBUG] GET https://dotnetcli.blob.core.windows.net/dotnet/Sdk/6.0/latest.version
Installing .NET SDK v6.0.400.
2022/08/09 20:57:05 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/dotnetsdk/dotnetsdk-6.0.400.tar.gz
=== .NET - Publish (google.dotnet.publish@0.9.0) ===
Installing application dependencies.
--------------------------------------------------------------------------------
Running "dotnet restore --packages /layers/google.dotnet.publish/packages MyAPI/MyAPI.csproj (DOTNET_CLI_TELEMETRY_OPTOUT=true)"

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.400

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
  Restored /workspace/MyAPI.ServiceModel/MyAPI.ServiceModel.csproj (in 710 ms).
  Restored /workspace/MyAPI/MyAPI.csproj (in 1.32 sec).
  Restored /workspace/MyAPI.ServiceInterface/MyAPI.ServiceInterface.csproj (in 1.32 sec).
Done "dotnet restore --packages /layers/google.dotnet.publish/pack..." (2.261158141s)
--------------------------------------------------------------------------------
Running "dotnet publish -nologo --verbosity minimal --configuration Release --output bin --no-restore --packages /layers/google.dotnet.publish/packages MyAPI/MyAPI.csproj (DOTNET_CLI_TELEMETRY_OPTOUT=true)"
  MyAPI.ServiceModel -> /workspace/MyAPI.ServiceModel/bin/net6.0/MyAPI.ServiceModel.dll
/workspace/MyAPI.ServiceInterface/Helpers/EasyHttp.cs(132,55): warning CS8509: The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '""' is not covered. [/workspace/MyAPI.ServiceInterface/MyAPI.ServiceInterface.csproj]
  MyAPI.ServiceInterface -> /workspace/MyAPI.ServiceInterface/bin/net6.0/MyAPI.ServiceInterface.dll
  MyAPI -> /workspace/MyAPI/bin/net6.0/MyAPI.dll
  MyAPI -> /workspace/bin/
Done "dotnet publish -nologo --verbosity minimal --configuration R..." (2.197984381s)
Determining entrypoint from output directory bin and project file MyAPI/MyAPI.csproj
=== .NET - Runtime (google.dotnet.runtime@0.9.1) ===
Found runtimeconfig.json file: MyAPI/bin/net6.0/MyAPI.runtimeconfig.json
Found runtimeconfig.json file: MyAPI/bin/net6.0/win-x64/MyAPI.runtimeconfig.json
Failure: (ID: 059beeeb) Failed to run /bin/build: at least one 'runtimeconfig.json' under ${GOOGLE_BUILDABLE}="MyAPI" is expected
--------------------------------------------------------------------------------
Sorry your project couldn't be built.
Our documentation explains ways to configure Buildpacks to better recognise your project:
 -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
If you think you've found an issue, please report it:
 -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
--------------------------------------------------------------------------------
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

**Comment by EatonZ** [comment]
Hello again, I need to get a new update out for my app, can you clarify what I need to do to fix? @jinglundong

**Comment by jinglundong** [comment]
Sorry for the late response. I just came back from a vacation. 

Could you share how you call `pack`? 

I think the problem is: the dotnet builder expects a runtimeconfig.json file under `MyAPI/bin/Release`. However, the generated runtimeconfig.json files are located at `MyAPI/bin/net6.0/MyAPI.runtimeconfig.json` and `MyAPI/bin/net6.0/win-x64/MyAPI.runtimeconfig.json`. There might be something wrong with how we `publish` the app. An other possibility is that I made a wrong assumption about the location. 

To unblock your `pack build` usage, you could checkout a previous commit of this repo. Sorry for the inconvenience.

**Comment by EatonZ** [comment]
@jinglundong Here is my pack usage:
`pack build --builder "gcr.io/buildpacks/builder:v1" --env GOOGLE_BUILDABLE="MyAPI" --publish "$REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME"`

**Comment by jinglundong** [comment]
@MontyCarter is working on this area. We will take a close look. Since you are using `pack` directly, I hope you could check out a previous git commit and unblock temporarily while we investigate this.

**Comment by EatonZ** [comment]
@jinglundong How would I modify the command above to use the last version before these changes?

**Comment by jinglundong** [comment]
I think what you need is 1) checkout a previous commit of this repo (`git checkout`), 2) create a builder locally (https://github.com/GoogleCloudPlatform/buildpacks/blob/main/CONTRIBUTING.md#creating-a-builder) 3) specify it via `--builder` when you call `pack build`. 

If you need more detailed instructions, I could probably provide more details later this week.

**Comment by EatonZ** [comment]
I can wait for a fix. Let me know when you commit any updates - thanks!

**Comment by EatonZ** [comment]
Hi! Will you have time to check it out soon?

**Comment by jinglundong** [comment]
https://github.com/GoogleCloudPlatform/buildpacks/commit/9c7eaf0c0fc16bb867134f2792f007132ea44928 may have your problem fixed. Could you check it and let us know if it works?

**Comment by EatonZ** [comment]
@jinglundong Just tried - same error.

**Comment by jinglundong** [comment]
From my reading of https://github.com/GoogleCloudPlatform/buildpacks/commit/9c7eaf0c0fc16bb867134f2792f007132ea44928#diff-1bd2f881be70abdc8506709a95c5f6e7c1e1ca5c05bce813fe6276fd38dd9c33R216, 
setting the environment var GOOGLE_ASP_NET_CORE_VERSION to a valid dotnet3 version (actually any valid dotnet3 semver) should bypass the runtimeconfig check. Does it work?

**Comment by EatonZ** [comment]
@jinglundong It works! Thanks. That will work for now, but I suggest still looking into fixing the runtimeconfig issue. In my project, that file is located here: `\MyAPI\MyAPI\bin\net6.0\win-x64\MyAPI.runtimeconfig.json`

Why is it not found?

**Comment by jinglundong** [comment]
Glad to hear that it worked for you. 

It seems like the runtime buildpack was able to identify two runtimesconfig files, but failed the regex/path matching. I will likely need to ask @MontyCarter to take a closer look when he comes back to the office.

```
=== .NET - Runtime (google.dotnet.runtime@0.9.1) ===
Found runtimeconfig.json file: MyAPI/bin/net6.0/MyAPI.runtimeconfig.json
Found runtimeconfig.json file: MyAPI/bin/net6.0/win-x64/MyAPI.runtimeconfig.json
Failure: (ID: 059beeeb) Failed to run /bin/build: at least one 'runtimeconfig.json' under ${GOOGLE_BUILDABLE}="MyAPI" is expected
```

**Comment by EatonZ** [comment]
Ok, let me know if you make any changes and I can re-test.🙂

**Comment by EatonZ** [comment]
@jinglundong @MontyCarter Had a chance to take a look yet?

**Comment by jinglundong** [comment]
Hi @EatonZ , could you re-test? It might be fixed by https://github.com/GoogleCloudPlatform/buildpacks/commit/c55ef274167be9c117a3d0fc2ef1160298071bdc.

**Comment by EatonZ** [comment]
@jinglundong Oh, I'll have to check! Unfortunately my power is gone due to hurricane, so it'll be some time before I can confirm.

**Comment by EatonZ** [comment]
@jinglundong @MontyCarter It's better - no longer fails, but still not where it should be. It is choosing the year-old base version (6.0.0) instead of the latest version (6.0.10). Relevant logs:

```
Determined runtime version from /layers/google.dotnet.publish/publish/bin/MyAPI.runtimeconfig.json: 6.0.0
WARNING: Not deleting folder: /workspace/bin
Determining entrypoint from output directory /layers/google.dotnet.publish/publish/bin and project file MyAPI/MyAPI.csproj
=== .NET - Runtime (google.dotnet.runtime@0.9.1) ===
Determined runtime version from GOOGLE_ASP_NET_CORE_VERSION: 6.0.0
Installing  v6.0.0.
2022/10/24 22:59:50 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/aspnetcore/aspnetcore-6.0.0.tar.gz
```

`--env GOOGLE_ASP_NET_CORE_VERSION="6.x.x"` is still needed to get it to use 6.0.10.

**Comment by EatonZ** [comment]
@jinglundong @MontyCarter Further thoughts on this?

**Comment by jinglundong** [comment]
Sorry for the late response @EatonZ. I totally missed your comment on Oct 24th. 

I believe the current design is to support latest dotnet version via semver like `--env GOOGLE_ASP_NET_CORE_VERSION="6.x.x"`. We will unlikely to change this behavior in the short term to be honest.
