### ISSUE TITLE
PHP buildpacks not suitable for local dev

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#218]
It looks like buildpacks are the only way to replicate App Engine environment locally. The limitation is - they are developed with production in mind.

Key problems are:
- `composer install` running with `--no-dev`
- php.ini got `opcache.enable=true` and would not react to code changes

Are there any recommendations? Would it make sense to update this repo to accept some dev-related flags?

**Comment by sl0wik** [comment]
I'm working on some solutions:
- `php.ini``opcache.enable=true` could be resolved per project with php.dev.ini + `.gcloudignore` that should ignore it during gcloud deployment.
- composer could support env `COMPOSER_ARGS` or `COMPOSER_FLAGS` that would override https://github.com/GoogleCloudPlatform/buildpacks/blob/df6e1b0001d25405a4ce1a774da54ecb65c1ea8f/pkg/php/php.go#L178

**Comment by sl0wik** [comment]
In case someone will need it, the solution for disabling opcache on local:
- Create `php.local.ini`
- Add to `php.local.ini` line `opcache.enable=false`
- Add to `.gcloudignore` line `php.local.ini`

This way `php.local.ini` will apply on local build, but on production it will be skipped because of `.gcloudignore`.

**Comment by sl0wik** [comment]
https://github.com/GoogleCloudPlatform/buildpacks/pull/219

**Comment by sl0wik** [comment]
I will make another PR that will check `DEV_MODE` flag instead. I would recommend adding an option to customize composer flags in the future anyway, mainly because of the possibility to run unit tests inside buildpacks. Most of projects running PHPUnit on deployment, and it would work on current version if composer is installed without `--no-dev`.

**Comment by spew** [comment]
HI @sl0wik no reason to change your PR, I was just musing about DEV_MODE and this was more for the google team.

**Comment by sl0wik** [comment]
Ok. I saw considered `DEV_MODE` variable before but it appeared that option to customize `COMPOSER_ARGS` would be way more flexible.

**Comment by sl0wik** [comment]
Currently, php81 would throw `Fork support is only compatible with the epoll1 and poll polling strategies` on `php artisan tinker`. The solution is adding `GRPC_POLL_STRATEGY=poll` to env (ref.: https://github.com/grpc/grpc/issues/29044#issuecomment-1068244652).

**Comment by matthewrobertson** [comment]
Sounds like the orginal issue reported here was resolved by https://github.com/GoogleCloudPlatform/buildpacks/pull/219
