### ISSUE TITLE
Python-specific requirements are not documented in readme

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#22]
Similar to #19, I am now trying https://github.com/GoogleCloudPlatform/buildpack-samples/blob/master/sample-python.

It's clear to me that some buildpacks have `Procfile` and some don't. This one clearly requires a Procfile.

Similarly there's a `runtime.txt` with `python-3.7.6` that I didn't see in `sample-node`. Issues about this:

1. why the inconsistency between samples (is python's runtime.txt required?)
2. is `runtime.txt` a replacement for GOOGLE_RUNTIME ? if so, it's not documented.

It would be **great** to formalize per-language detection mechanisms and how each language needs to use these customizations and whether they are optional or not.

**Comment by lukasberger** [comment]
`runtime.txt` is not required and in fact not supported. I believe the samples repo has it to support the Heroku builder. We support `.python-version` as well as `GOOGLE_RUNTIME_VERSION` as the mechanism for specifying runtime version for Python.

All buildpacks support `Procfile`, but it is not required for languages other than Python as we have mechanism to infer the start command. The environment variable equivalent is `GOOGLE_ENTRYPOINT`.

The detection mechanism is as follows:
1. If `GOOGLE_RUNTIME` is set, use buildpacks for that language.
1. If not, rely on auto-detection (based on files).
1. If `GOOGLE_RUNTIME_VERSION` is set, install the specified version of the runtime.
1. If not, use the language-idiomatic way of specifying runtime version, e.g. package.json for Node.js, .python-version for Python, etc.

Agreed that it would be great to formalize language detection in the README. Thank you for the suggestion.

**Comment by ahmetb** [comment]
cc: @jamesward 

> believe the samples repo has it to support the Heroku builder.

if that's the case we should prob delete that file to avoid confusion for buildpack-samples audience.

**Comment by ahmetb** [comment]
> All buildpacks support `Procfile`, but it is not required for languages other than Python

I think this is definitely worth documenting as well. We can assume everyone knows and have used buildpacks to curate the docs, but that will leave out a lot of the first-time users.

So I'm in general happy with the current state in Node, Go etc. However almost always any non-trivial user will have to use cmd line args to customize this and that, so it is important probably to say "there's a file called Procfile and this is how you can use it".

**Comment by jamesward** [comment]
Most of these samples were originally created to show Cloud Run Button + Buildpacks using Heroku's buildpacks.  But now that we've got them all working with our buildpacks you are right that there needs to be some cleanup.  I've removed that `runtime.txt` and will see if there is any other stuff that needs cleanup.

**Comment by jama22** [comment]
Documented in https://cloud.google.com/docs/buildpacks/python#application_entrypoint
