### ISSUE TITLE
Dart buildpack fails to compile Dart functions-framework source

### ISSUE THREAD

**Issue by taeold** [GoogleCloudPlatform/buildpacks#222]
Today, I tried following the [instructions](https://github.com/GoogleCloudPlatform/functions-framework-dart/blob/main/docs/quickstarts/03-quickstart-cloudrun.md) for deploying a Dart + Functions Framework to Google Cloud Run.

I'm stuck with  the following error message in the Cloud Build job:

```
[builder] === Dart - Compile (google.dart.compile@1.0.0) ===
[builder] --------------------------------------------------------------------------------
[builder] Running "dart run build_runner build --delete-conflicting-outputs"
[builder] Could not find a file named "pubspec.yaml" in "/layers/google.dart.pub/pub/hosted/pub.dartlang.org/_fe_analyzer_shared-43.0.0".
```

I tried to reproduce the issue locally and found that if I delete the following line setting `PUB_CACHE` environment variable in the `dart/pub` buildpack, the build succeeds:

https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/dart/pub/main.go#L49

I'm new to both Buildpack and Dart, and don't know what the consequence of moving that line is.

Anyone here willing to help diagnose the issue further?

**Comment by matthewrobertson** [comment]
The `PUB_CACHE` env var is only trying to re-use dependencies between builds in improve perf. If it is breaking things we should remove it. This was working before so it would be good to understand what changed. To me it sounds like it could be a regression in the functions framework.

@kevmoo might be able to help us.

**Comment by kevmoo** [comment]
Gah! I've SEEN this issue before. It's a weird [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug).

See also
https://github.com/dart-lang/pub/issues/2460
https://stackoverflow.com/questions/64223104/could-not-find-a-file-named-pubspec-yaml-when-auto-generating-code-with-build

This feels like a caching issue.

@taeold – could you point me to the source you're trying to deploy?

**Comment by matthewrobertson** [comment]
@taeold does this repro consistently when you build locally with `pack`? If so could you try and pass the `--clear-cache` flag to `pack build`?

```
pack build my-app --builder gcr.io/buildpacks/builder:v1 --clear-cache
```

**Comment by kevmoo** [comment]
```
=== Dart - Compile (google.dart.compile@1.0.0) ===
--------------------------------------------------------------------------------
Running "dart run build_runner build --delete-conflicting-outputs"
Could not find a file named "pubspec.yaml" in "/layers/google.dart.pub/pub/hosted/pub.dartlang.org/_fe_analyzer_shared-43.0.0".
#0      new Pubspec.load (package:pub/src/pubspec.dart:307:7)
#1      new Package.load (package:pub/src/package.dart:128:29)
#2      SystemCache.load (package:pub/src/system_cache.dart:105:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:119:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:114:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:250:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:301:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:66:29)
#13     main (file:///b/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

So it's not just you! Will investigate!

**Comment by taeold** [comment]
Looks like you already have a repro, but just in case it helps, I was trying to deploy [Hello World example](https://github.com/GoogleCloudPlatform/functions-framework-dart/tree/main/examples/hello) from Dart Functions Framework.

Both `gcloud run deploy --source=.` and `pack build --builder gcr.io/buildpacks/builder:v1 hellodart` was failing in the exact same way for me ("Could not find a file named "pubspec.yaml") at `dart/compile` buildpack

**Comment by kevmoo** [comment]
The weird thing: I see that exact version of `_fe_analyzer_shared` getting downloaded earlier.

This is tricky to debug, too. Hrm...

**Comment by taeold** [comment]
Here's another diff that seems to fix the problem I'm seeing:

```
diff --git a/cmd/dart/pub/main.go b/cmd/dart/pub/main.go
index 9807b4a..91b3ff4 100644
--- a/cmd/dart/pub/main.go
+++ b/cmd/dart/pub/main.go
@@ -47,6 +47,9 @@ func buildFn(ctx *gcp.Context) error {
                return fmt.Errorf("creating %v layer: %w", pubLayer, err)
        }
        ml.BuildEnvironment.Override("PUB_CACHE", ml.Path)
+       if err := ctx.Setenv("PUB_CACHE", ml.Path); err != nil {
+               return err
+       }
        if _, err := ctx.Exec([]string{"dart", "pub", "get"}, gcp.WithUserAttribution); err != nil {
                return err
        }
```

My guess here is that `ml.BuildEnvironment.Override("PUB_CACHE", ml.Path)` does not immediately set the `PUB_CACHE` environment variable to the subsequent `dart pub get` execution.

I saw log entries like below when I passed `--verbose` flag to `dart pub get` command:

```
[builder]     |     {
[builder]     |       "name": "yaml",
[builder]     |       "rootUri": "file:///home/cnb/.pub-cache/hosted/pub.dartlang.org/yaml-3.1.1",
[builder]     |       "packageUri": "lib/",
[builder]     |       "languageVersion": "2.12"
[builder]     |     },
```

Note the `rootUri` - the fetched package are being stored in the `~/.pub-cache` directory instead.

After explicitly setting the `PUB_CACHE` environment variable, I saw that the cached packages are stored in expected location:

```
[builder]     |     {
[builder]     |       "name": "yaml",
[builder]     |       "rootUri": "file:///layers/google.dart.pub/pub/hosted/pub.dartlang.org/yaml-3.1.1",
[builder]     |       "packageUri": "lib/",
[builder]     |       "languageVersion": "2.12"
[builder]     |     },
```

I don't have any idea why things suddenly started behaving this way.

**Comment by matthewrobertson** [comment]
@taeold you are right, `ml.BuildEnvironment.Override` only sets the env var for subsequent buildpacks. Putting up a fix now.
