### ISSUE TITLE
npm prune step does not remove devDependencies

### ISSUE THREAD

**Issue by steverandy** [GoogleCloudPlatform/buildpacks#224]
I tried to deploy a basic node.js app that has devDependencies.
It has a build step, so I included the `gcp-build` script in package.json file.

When I checked the build log, the npm prune step got executed, but it appears that it did not remove any of the devDependencies.
I've verified this by comparing the build image size of a build that has devDependencies vs no devDependencies. Both have identical image size.

I've also compared running the npm prune in my localhost with `NODE_ENV=production npm prune` and the log output is different (about half no of packages reported in my localhost).

**Comment by matthewrobertson** [comment]
Thanks for reporting this @steverandy. Could you tell me more about how you were building the app when the when the dev dependencies were not pruned? Were you deploying to App Engine or Google Cloud Functions? My first thought is that the `NODE_ENV` is not being set correctly, but I will need to understand more about how to repro this in order to chase it down.

**Comment by steverandy** [comment]
Deploying to Cloud Run. I will try to deploy a demo app and share the log with you.

If user does not set any `NODE_ENV`, is it correct to assume that `buildpacks` will prune the `devDependencies` (if any)?

**Comment by GeorgiJefferski** [comment]
Any news on this one?

I have the same issue using `gcloud app deploy app.yaml`. No matter if I set env variable `NODE_ENV: production` or not, when `gcp-build` command (compiling TypeScript to JavaScript) has been executed, it is followed by `npm prune` which installs both dependencies and devDependencies (Cloud Build logs). And according to [this ](https://cloud.google.com/appengine/docs/standard/nodejs/running-custom-build-step)doc:

> "After executing your custom build step, App Engine removes and regenerates the node_modules folder by only installing the production dependencies declared in the dependencies field of your package.json file.".

**Comment by matthewrobertson** [comment]
According to [the npm docs](https://docs.npmjs.com/cli/v8/commands/npm-prune), it seems we are doing the right thing:

> If the --production flag is specified or the NODE_ENV environment variable is set to production, this command will remove the packages specified in your devDependencies

[Here](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/nodejs/npm/main.go#L128) is where the buildpacks are running `npm prune`. Interestingly the `shouldPrune` function in that file emits logging if it will skip this step. Are you folks seeing any logging about "Retaining devDependencies")?

**Comment by GeorgiJefferski** [comment]
@matthewrobertson There is only `Step #2 - "build": Running "npm prune"` log, no `"Retaining devDependencies because..."` log.
I am not a Go engineer, but shouldn't `gcp.WithEnv("NODE_ENV="+nodeEnv)` be placed [here](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/nodejs/npm/main.go#L128)?

**Comment by kennethye1** [comment]
It's probably the case that we set the nodeEnv to development [here](https://github.com/GoogleCloudPlatform/buildpacks/blob/b7d38158cb7dabdb969266e029876af617820f5c/cmd/nodejs/npm/main.go#L79) which causes NODE_ENV=development to be set in the gcp.WithEnv function e.g. [here](https://github.com/GoogleCloudPlatform/buildpacks/blob/b7d38158cb7dabdb969266e029876af617820f5c/cmd/nodejs/npm/main.go#L93)

**Comment by kennethye1** [comment]
Should be fixed now. 4a5e4e0
