### ISSUE TITLE
Yarn2 workspace focus regression

### ISSUE THREAD

**Issue by tilgovi** [GoogleCloudPlatform/buildpacks#225]
With f3ac43007d38b7dd2a94ce3c2f0d2cf498f91e9b, `yarn workspaces focus` is run regardless of the result of `HasYarnWorkspacePlugin`, which will fail when the workspaces plugin is absent. This is a regression from the behavior before that commit, wherein the buildpack would skip running `yarn workspaces focus`.

**Comment by spew** [comment]
Hi @tilgovi thanks for reporting this and the excellent debugging. We are working on a fix.

**Comment by spew** [comment]
This has been fixed but is only rolled out to `cloud run deploy`. It is not yet available for functions and appengine builds.

**Comment by tilgovi** [comment]
@spew is there any place that I can monitor for when buildpack changes roll out to functions?

**Comment by spew** [comment]
We don't have a way for you to programatically monitor, however, you can try running a `gcloud functions deploy` and take a look at the associated build that is produced. The 'name' of each build step is a docker image. When the tag of the image changes then we have done a release.

If your builds are using image with tag `nodejs16_20220821_16_16_0_RC00` then you have the latest changes.

**Comment by spew** [comment]
@tilgovi I don't have a test application for this issue (or else I would verify myself), has this issue been fixed for you?

**Comment by tilgovi** [comment]
Looking good. Thank you.
