### ISSUE TITLE
Python functions: build did not realize main.py was missing

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#23]
`func.py`:

```
def hello(request):
    return "Hello world!"
```

`requirements.txt`:

```
functions-framework==1.4.1
```

Upon building and running this function, I get:

```
  File "/layers/google.python.pip/pip/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/layers/google.python.pip/pip/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/layers/google.python.pip/pip/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/layers/google.python.pip/pip/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/layers/google.python.pip/pip/functions_framework/_cli.py", line 37, in _cli
    app = create_app(target, source, signature_type)
  File "/layers/google.python.pip/pip/functions_framework/__init__.py", line 130, in create_app
    raise MissingSourceException(
functions_framework.exceptions.MissingSourceException: File /workspace/main.py that is expected to define function doesn't exist
```

It would be nice to:

1. catch during build step `main.py` doesn't exist when GOOGLE_FUNCTION_TARGET specified.
2. document this requirement (I should be able to develop a func without buildpacks ideally without bouncing much between repos).

**Comment by di** [comment]
@ahmetb I'm a little confused here, do you have a typo? In this example it looks like you have a `main.py`, I wouldn't expect that exception to raise.

Did you mean when you have a source file _other_ than `main.py`, and `GOOGLE_FUNCTION_SOURCE` isn't specified?

**Comment by ahmetb** [comment]
I meant to say func.py. I will edit.

**Comment by di** [comment]
Got it! I think ideally all the function buildpacks should fail to build if `GOOGLE_FUNCTION_SOURCE` does not exist, regardless of whether the user has set it or if the default is being used.
