### ISSUE TITLE
Not able to build when "engine.node" : ">=18"

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpacks#230]
GCP Buildpacks are not able to build this Node.js 18 sample: https://github.com/steren/cloud-run-node-18

Note the `engines.node` that is requiring `>=18`. This is a [valid value](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines)

Is it because Buildpacks do not support Node.js 18 yet? Node.js 18 is the [current major version and will be the actived LTS in October 2022](https://nodejs.org/en/about/releases/).

**Comment by spew** [comment]
Hi @steren Yes, that is correct. We are working on a nodejs18 release for Q4.

**Comment by spew** [comment]
Yes, that is correct, however, Nodejs18 did not work on Ubuntu 18. Until recently we have only supported Ubuntu 18 and we are in the process of reworking our systems to support N operating systems, including Ubuntu22 and beyond.
