### ISSUE TITLE
Unable to build Cloud Function where Go module version is >v1

### ISSUE THREAD

**Issue by engvik** [GoogleCloudPlatform/buildpacks#231]
If the Go module containing the Cloud Function has a major version above 1, it fails to build.

Here is a minimal example to reproduce:

1) Init go modules with version 2:

```
go mod init example.com/entrypoint/v2
```

2) Create a simple function, `entrypoint.go`:

```go
package entrypoint

import (
        "log"
        "net/http"
)

func Entrypoint(w http.ResponseWriter, r *http.Request) {
        log.Println("hello")
}
```

3) Build:

```
pack build --builder gcr.io/buildpacks/builder:v1 --env GOOGLE_FUNCTION_SIGNATURE_TYPE=http --env GOOGLE_FUNCTION_TARGET=Entrypoint my-function
```

4) Producing the following error:

```
Failure: (ID: 03382a83) go: errors parsing go.mod:
/workspace/go.mod:5: require example.com/entrypoint/v2: version "v0.0.0" invalid: should be v2, not v0
```

By skimming through the functions framework code, it seems like that versioning isn't taken into account. If I understand correctly, the output from `go list -m` ([src](https://github.com/GoogleCloudPlatform/buildpacks/blob/461e66e6498fb21d7448bd7e237bff12f7e2c46e/cmd/go/functions_framework/main.go#L261)) is used as input for a new `go.mod` file, which requires the Cloud Function to be built as a dependency with version `v0.0.0`. In this case it would require the module with the command `go mod edit -require example.com/entrypoint/v2@0.0.0` ([src](https://github.com/GoogleCloudPlatform/buildpacks/blob/461e66e6498fb21d7448bd7e237bff12f7e2c46e/cmd/go/functions_framework/main.go#L181-L183)). This would cause Go modules to complain and display the error I'm seeing.

**Comment by anniefu** [comment]
Thanks for feedback! This is fixed with the latest builder release.
