### ISSUE TITLE
ubuntu base image outdated

### ISSUE THREAD

**Issue by unnimona** [GoogleCloudPlatform/buildpacks#232]
the base image 
ubuntu 22.04 base image needed

gcr.io/buildpacks/builder:v1  is outdated

**Comment by jama22** [comment]
Thanks for the feedback. Our team is currently working on introducing Ubuntu 22.04 as the new base image for gcr.io/buildpacks/builder 

When the work is complete, we expect the new tag to be gcr.io/buildpacks/builder:latest

**Comment by jama22** [comment]
@unnimona  we jsut released our first version of the Ubuntu-22 builder, you can give it a try using the `google-22` tag on the builder. For example, if you're using pack you can do this:

```
pack build --builder=gcr.io/buildpacks/builder:google-22 <image name> 
```

**Comment by jama22** [comment]
Made a small announcement outlining how to use the new Ubuntu-22 base image. PTAL @unnimona and provide feedback if you have any comments
