### ISSUE TITLE
Improve error messaging when trying to build non-AspNetCore .NET App

### ISSUE THREAD

**Issue by juhani-honkala** [GoogleCloudPlatform/buildpacks#237]
**Update: It seems the project must be of type "Microsoft.AspNetCore.App" and anything else fails with the error below. It might be a good idea to change the error message to reflect this, instead of a very generic "couldn't find runtime version" error.**

--

I am trying to build & run a .NET 6.0 project in GCP Cloud Run with the buildpack automation. After building the app Buildpack complains "couldn't find runtime version from runtimeconfig.json".
```
Done "dotnet publish -nologo --verbosity minimal --configuration R..." (31.282676918s)
Step #0 - "Buildpack": Determining entrypoint from output directory bin and project file TestConsole/TestConsole.csproj
Step #0 - "Buildpack": === .NET - Runtime (google.dotnet.runtime@0.9.1) ===
Step #0 - "Buildpack": Failure: (ID: 224c5ea3) Failed to run /bin/build: couldn't find runtime version from runtimeconfig.json: &dotnet.RuntimeConfigJSON{RuntimeOptions:dotnet.runtimeOptions{TFM:"net6.0", Framework:dotnet.framework{Name:"Microsoft.NETCore.App", Version:"6.0.0"}, Frameworks:[]dotnet.framework(nil), ConfigProperties:dotnet.configProperties{SystemGCServer:false}}}
```

The runtime config file looks like this and it seems to have runtime version information there, or is something missing?

```
{
    "runtimeOptions": {
      "tfm": "net6.0",
      "framework": {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      "configProperties": {
        "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
      }
    }
  }
```

Any help would be greatly appreciated!

**Comment by matthewrobertson** [comment]
I agree the error messaging is confusing here. I am happy to hear it sounds like you figured things out.

**Comment by kritkasahni-google** [comment]
Fixed the message to provide more specific requirements for Microsoft.AspNetCore.App
