### ISSUE TITLE
Support PHP and Ruby in the general builder (parity for Cloud Run Button)

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/buildpacks#24]
We'd like to make this builder image the default builder image in Cloud Run Button but we need some additional buildpacks:
- Ruby
- PHP
- Scala / sbt

I'd be happy to take on building the Scala one since I'm probably the only one that'll use it. :)

**Comment by ahmetb** [comment]
This is is a bit of run-button scoped discussion but I recommend we go ahead and take a look at how many repos are actually using buildpacks. If it's a manageable small number (which I'd expect), let's flip the default to google already –and allow custom builders through config file or url.

**Comment by jamesward** [comment]
I have some samples that'll break until we get the php & sbt support in.  Once we get https://github.com/GoogleCloudPlatform/cloud-run-button/issues/170 done, then I can `app.json` them to use the heroku buildpacks.

**Comment by grant** [comment]
I was looking and saw the description in pack:

```
	Google:                gcr.io/buildpacks/builder:v1
Ubuntu 18 base image with buildpacks for .NET, Go, Java, Node.js, and Python       
```

But it looks like we have buildpacks for Ruby and PHP?
https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/gcf

**Comment by lukasberger** [comment]
PHP and Ruby. are only supported in the GAE/GCF builders where the runtime is part included in the stack images. We don't have a `runtime` buildpack for either, yet.

**Comment by steren** [comment]
Cloud Run customers are looking at using GCP Buildpacks for Ruby and PHP (via Cloud Run's continuous deployment from git feature, or deploy from local source feature). Notably in order to migrate from App Engine.

**Comment by iamacarpet** [comment]
Thanks @steren ,

As one of these customers, we've managed to use the App Engine buildpack images to get running on GCR:

Taken from: gcr.io/gae-runtimes/buildpacks/php74/builder

https://github.com/a1comms/GaeSupportLaravel/blob/php7.4-laravel6.0/docs/examples/laravel/buildpack-cloud-run/cloudbuild_LIVE.yml

It's a little frustrating the way things are tagged when trying to find the latest version, you can tell it isn't designed for external use.

It's hard to have confidence in using these when it's so obviously "officially unsupported".

**What needs to happen for this language to make it into the general builder? Or, will it ever happen?**

As a note, the only other thing we've struggled with is static file handling, for files versioned alongside the application.

App Engine had static file handlers in `app.yaml`, whereas in GCR and using this buildpack, we've had to make the PHP app itself serve the static files, where the idiomatic way to do it would be via nginx (which is in the container, but the config doesn't support it).

Our hope is that if the runtime image (and `serve` come out into the open), these can be modified to better support the use case.

**Comment by steren** [comment]
I'm an personally advocating internally for this issue to be picked up. It is not intended for customers to have to use the undocumented GAE buildpacks.

**Comment by iamacarpet** [comment]
Thanks @steren , really appreciate that!

We’ve spoken a lot to Matt L about it too, but I get the impression his team don’t own these buildpacks either.

Can you divulge what the ownership structure looks like?

Is it Matt S, since he presented the demo vid at NEXT?

**Comment by steren** [comment]
I can confirm that the right owners are aware of the request.

**Comment by jasonjho** [comment]
Any updates on this?

**Comment by jama22** [comment]
A few years later but we got both Ruby and PHP buildpacks going on the [generic builders](https://cloud.google.com/docs/buildpacks/builders). We don't currently have plans to introduce Scala support. If folks feel strongly about a Scala buildpack, I'd encourage ya'll to open a new issue and we can have a conversation around that possibility.
