### ISSUE TITLE
Failed to build pyarrow

### ISSUE THREAD

**Issue by expressintegrations** [GoogleCloudPlatform/buildpacks#242]
I haven't changed anything recently in my project, but when I tried to deploy it last, I received this error in the logs: `ERROR: Could not build wheels for pyarrow, which is required to install pyproject.toml-based projects`

See the full log here: 
[log-d20114fe-3eeb-4a8d-8926-3a971882894c.txt](https://github.com/GoogleCloudPlatform/buildpacks/files/10018377/log-d20114fe-3eeb-4a8d-8926-3a971882894c.txt)

This is my `requirements.txt`: 
[requirements.txt](https://github.com/GoogleCloudPlatform/buildpacks/files/10018383/requirements.txt)

**Comment by matthewrobertson** [comment]
Sorry to hear you have having trouble. From the build logs it looks like you are not specifying a Python version for your application so we are installing the latest available version, which is Python `3.11.0`. It looks like `pyarrow` only recently landed support for `3.11`, so it is likely not available in the version your app is using (see https://github.com/apache/arrow/pull/14499 and https://github.com/streamlit/streamlit/issues/5608). My advice is to add a `.python-version` file to your application root and pin to Python 3.10 for now:

```
3.10.x
```

**Comment by smsohan** [comment]
@expressintegrations can you share a little bit about where you're deploying this container?

**Comment by expressintegrations** [comment]
I am using cloud run and cloud build to deploy changes to my project synced with a git repository. I opted to use the cloud build inline yaml file to manage the build/deployment.

**Comment by smsohan** [comment]
Thank you.
