### ISSUE TITLE
Unable to deploy to App Engine

### ISSUE THREAD

**Issue by crivotz** [GoogleCloudPlatform/buildpacks#244]
Hi all,
I hope I am writing in the correct repository.
I just found out today that I can no longer deploy my projects to app engine due to the following error.

```
Step #2 - "build": --------------------------------------------------------------------------------
Step #2 - "build": Running "mv .bundle /layers/google.ruby.bundle/gems/.bundle"
Step #2 - "build": Done "mv .bundle /layers/google.ruby.bundle/gems/.bundle" (4.633740168s)
Step #2 - "build": === Node.js - Yarn (google.nodejs.yarn@2.1.0) ===
Step #2 - "build": 2022/11/16 22:32:59 [DEBUG] GET https://registry.npmjs.org/yarn
Step #2 - "build": DEBUG: ***** CACHE MISS: "yarn_engine"
Step #2 - "build": Installing Yarn v1.22.19
Step #2 - "build": 2022/11/16 22:32:59 [DEBUG] GET https://yarnpkg.com/downloads/1.22.19/yarn-v1.22.19.tar.gz
Step #2 - "build": DEBUG: Setting environment variable PATH=/layers/google.nodejs.yarn/yarn_engine/bin:/layers/google.ruby.runtime/ruby/bin:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Step #2 - "build": --------------------------------------------------------------------------------
Step #2 - "build": Running "node -v"
Step #2 - "build": Done "node -v" (185.037µs)
Step #2 - "build": Failure: (ID: 653c7ba4) executing command "node -v": exec: "node": executable file not found in $PATH
Step #2 - "build": --------------------------------------------------------------------------------
```

They are Ruby on Rails application on `runtime: ruby27`. Last working deploy was 8 November 2022
I have already tried having the `yarn.lock` file regenerated or adding any `engines` on the `package.json` but no results.

Thanks

**Comment by shreejad** [comment]
Hi, acknowledged. I'm taking a look at it.

**Comment by shreejad** [comment]
@crivotz Can you please share the entire builder output?

**Comment by shreejad** [comment]
I know why this might be happening. The builder finds the "yarn.lock" file and tries to install Yarn. To install Yarn, we need Node installed. The builder is not installing Node because the app does not need asset precompilation.

Short term fix: Remove yarn.lock because App Engine does not use it.

**Comment by shreejad** [comment]
@crivotz If you need `yarn.lock` for local development, I would suggest adding a `.gcloudignore` file in the root directory that mentions `yarn.lock`. This will ensure `yarn.lock` is not uploaded to App Engine and the Ruby builder does not try to install Yarn without installing Node.

More information on `.gcloudignore` - https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore

**Comment by crivotz** [comment]
Thank you very much it works perfectly
