### ISSUE TITLE
GOOGLE_FUNCTION_SOURCE not documented

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#25]
This was mentioned in https://github.com/GoogleCloudPlatform/buildpacks/issues/19#issuecomment-625956329

Apparently this env var exists but not documented. If the answer to this is "this is documented at functions-frameworks repo" I'll say let's try to give users enough info to at least have them write their own hello world from scratch in this repo.

If someone’s using buildpacks they might not be the best equipped audience to understand how this project works and relates to FF under the covers.

**Comment by ahmetb** [comment]
FWIW the link to FF we have https://cloud.google.com/functions/docs/functions-framework also doesn't talk about environment variables such as this.

**Comment by lukasberger** [comment]
I think the reason it's not documented on that page is because it's not supported by all runtimes (and not part of the contract). We can still document it in the README though and possibly also link to the contract/functions docs.
