### ISSUE TITLE
How do I specify java options ? 

### ISSUE THREAD

**Issue by kliarist** [GoogleCloudPlatform/buildpacks#263]
I am using gcr.io/buildpacks/builder to build my docker image. 

I have figured that 
* for setting the java version I need to use BP_JVM_VERSION file set to 17.*
* for controlling the log level I need to use BP_LOG_LEVEL file set to debug

how do I specify the java options to use when starting up the java jar within the image ? I have used JAVA_TOOL_OPTIONS, but that is being picked up by gradle buildpack. I want to specify a javaagent jar and JVM property.

Any help is welcome

**Comment by sriram-mahavadi** [comment]
If you are using your image to run on cloud run or cloud functions, please refer to - https://cloud.google.com/docs/buildpacks/service-specific-configs#google_entrypoint.

GOOGLE_ENTRYPOINT specifies the command that is run when your container is executed.

**Comment by kliarist** [comment]
I am using the gcr.io/buildpacks/builder builder image to build my docker image on gitlab as it does not require a docker daemon. 

That is exactly how I managed to specify JVM flags literally one hour ago.. via the GOOGLE_ENTRYPOINT.. I was just hoping that there is a more generic CNB way of doing so as GOOGLE_ENTRYPOINT is specific to the Google builder.

Anyhow, much appreciated

**Comment by kliarist** [comment]
Closing this for now

**Comment by jama22** [comment]
@kliarist that's actually a very interesting point. AFAIK the CNB specification for buildpacks leaves version pinning and language-specific options up to the implementer. This is why you might notice some differences between how the GCP java buildpacks work vs the Paketo Java buildpacks. 

If you're curious to learn more, I recently started a conversation about language pinning (as an example) in the CNB slack community https://cloud-native.slack.com/archives/C0333LG1E68/p1671219922120629
