### ISSUE TITLE
python39_20230116_3_9_16_RC00 image not found 

### ISSUE THREAD

**Issue by jthveolia** [GoogleCloudPlatform/buildpacks#264]
Hello,

Building of Python3.9 Cloud Function does not work anymore:
`Error response from daemon: manifest for [asia.gcr.io/fn-img/buildpacks/python39/builder:python39_20230116_3_9_16_RC00](http://asia.gcr.io/fn-img/buildpacks/python39/builder:python39_20230116_3_9_16_RC00) not found: manifest unknown: Failed to fetch "python39_20230116_3_9_16_RC00" from request "/v2/fn-img/buildpacks/python39/builder/manifests/python39_20230116_3_9_16_RC00`

I think it's because the image url changed from `asia.gcr.io/gae-runtimes/buildpacks/google-gae-18/python/builder:python310_20230116_3_10_9_RC00` to `asia.gcr.io/fn-img/buildpacks/python39/builder:python39_20230116_3_9_16_RC00`.

Can someone help?

**Comment by smsohan** [comment]
We're looking into this. Please try again and let us know if you're still seeing this issue.

**Comment by jinglundong** [comment]
Sorry for the inconvenience. We believe this issue has been mitigated by 2023-01-24 22:00:00 PST.

**Comment by jthveolia** [comment]
I confirm it's working again, now thank you.
