### ISSUE TITLE
failed to get GET https://dl.google.com/runtimes/ubuntu1804/python/version.json

### ISSUE THREAD

**Issue by Meerashine** [GoogleCloudPlatform/buildpacks#265]
I am trying to build the cloud function and is showing me this error. I have updated the .python-version with different python versions still cannot fix the error

**Comment by jinglundong** [comment]
Hi [Meerashine](https://github.com/Meerashine), do you mind sharing your .python-version file? Buildpacks should be able to support the following python versions on ubuntu1804. Do you see your version in the following list? Please note, we should be able to match partially, like mapping 3.10 to 3.10.9. 

["3.10.0","3.10.1","3.10.2","3.10.3","3.10.4","3.10.5","3.10.6","3.10.7","3.10.8","3.10.9","3.11.0","3.11.1","3.7.0","3.7.1","3.7.10","3.7.11","3.7.12","3.7.13","3.7.14","3.7.15","3.7.16","3.7.2","3.7.3","3.7.4","3.7.5","3.7.6","3.7.7","3.7.8","3.7.9","3.8.0","3.8.1","3.8.10","3.8.11","3.8.12","3.8.13","3.8.14","3.8.15","3.8.16","3.8.2","3.8.3","3.8.4","3.8.5","3.8.6","3.8.7","3.8.8","3.8.9","3.9.0","3.9.1","3.9.10","3.9.11","3.9.12","3.9.13","3.9.14","3.9.15","3.9.16","3.9.2","3.9.3","3.9.4","3.9.5","3.9.6","3.9.7","3.9.8","3.9.9"]%

**Comment by jinglundong** [comment]
The error you shared may caused by the access control we set on https://dl.google.com/runtimes/ubuntu1804/python/version.json. Could you share more info to help us debug?

* how did you deploy your function? gcloud, pack CLI or deploy via the GCP console (UI). 
* Is this the full error message? 

Since this seems to be a GCF issue, https://cloud.google.com/functions/docs/troubleshooting contains troubleshooting info. You could find the contact info of GCP cloud support.

**Comment by jinglundong** [comment]
FYI, I'm able to deploy a hello world function with or without .python-version file. The test function I used is: https://github.com/GoogleCloudPlatform/python-docs-samples/tree/main/functions/helloworld. 

```
gcloud functions deploy python-http-function \
--gen2 \
--runtime=python38 \
--region=us-central1 \
--source=. \
--entry-point=hello_get \
--trigger-http \
--allow-unauthenticated
```

```
cat .python-version                           
3.8.5
```
From my reading of the cloud build log and my understanding of the functions creation logic, the python version in .python-version file has lower precedence comparing to the  python version specified at`--runtime`.

**Comment by matthewrobertson** [comment]
I think this was probably a transient issue with dl.google.com. I am not able to reproduce the issue.
