### ISSUE TITLE
GCP picking up Python3.10 builder for Python3.9 project

### ISSUE THREAD

**Issue by parthraghav** [GoogleCloudPlatform/buildpacks#273]
Hey all, I'm having trouble deploying a service to Google Cloud Run. I'm developing in Python 3.9 runtime, but App Engine is picking up Python 3.10 builder for some reason, which may be causing the build to fail as it's the only error log I'm receiving. Pre-buildpack stage succeeds, but the actual build fails. Need some help troubleshooting this.

Deploy Command
```
gcloud functions deploy transcribe \
--gen2 \
--runtime=python39 \
--source=. \
--entry-point=transcribe \
--trigger-http \
--allow-unauthenticated

```
Error
`ERROR: build step 1 \"[us-west3-docker.pkg.dev/gae-runtimes/gcp/buildpacks/google-gae-18/python/builder:python310_20230123a_3_10_9_RC00](http://us-west3-docker.pkg.dev/gae-runtimes/gcp/buildpacks/google-gae-18/python/builder:python310_20230123a_3_10_9_RC00)\" failed: step exited with non-zero status: 145`

Logs:
https://gist.github.com/parthraghav/b5abde2eafbe2de8f126eedbf2900c99

**Comment by smsohan** [comment]
The image path containing python 3.10 is confusing, but it's the correct one. We're in the process of making some changes and will soon rename these images.

In the meanwhile, it seems like the build of your python function is failing. Looks like this line in the log shows the failure
https://gist.github.com/parthraghav/b5abde2eafbe2de8f126eedbf2900c99#file-gcp-error-logs-L25643

**Comment by parthraghav** [comment]
Thanks for pointing out this error log. It looks like it's building some x86_64 image. Is it possible that the issue here is that I'm using an ARM64-M1 mac?

`Failure: (ID: c84b3231) ...2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)`

**Comment by parthraghav** [comment]
I discovered that the issue was caused by `torch==1.13.1` failing to build on GCP. I was able to resolve it by adding fallback requirements as follows:

```
-f https://download.pytorch.org/whl/cpu
-f https://download.pytorch.org/whl/torch_stable.html
--find-links https://download.pytorch.org/whl/cu113/torch_stable.html; sys_platform == "linux"
torch==1.10.2; sys_platform == "linux"
```
