### ISSUE TITLE
Kotlin http4k pack gets stuck after running gradlew

### ISSUE THREAD

**Issue by davidals** [GoogleCloudPlatform/buildpacks#282]
I have a very simple Kotlin application using http4k.
My main file is:

```
package com.sample

import org.http4k.core.Request
import org.http4k.core.Response
import org.http4k.core.Status.Companion.OK
import org.http4k.server.Undertow
import org.http4k.server.asServer

fun main() {
    { _: Request -> Response(OK).body("Hello World") }.asServer(Undertow(8000)).start()
}
```

And my build.gradle.kts is:
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.8.10"
    kotlin("plugin.serialization") version "1.8.10"
    application
}

group = "com.sample"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.http4k:http4k-client-okhttp:4.35.4.0")
    testImplementation(kotlin("test"))
    testImplementation("org.http4k:http4k-testing-hamkrest:4.35.4.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    implementation(platform("org.http4k:http4k-bom:4.36.0.0"))
    implementation("org.http4k:http4k-core")
    implementation("org.http4k:http4k-format-jackson:4.36.0.0")
    implementation("org.http4k:http4k-server-undertow")
    implementation("org.http4k:http4k-client-apache")
}

tasks.test {
    useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

application {
    mainClass.set("com.sample.MainKt")
}
```

If I run `./gradlew clean assemble -x test --build-cache --quiet` it succeeds,
But when I run: `pack build --builder=gcr.io/buildpacks/builder:v1 sample` it gets stuck with this log:

```
1: Pulling from buildpacks/builder
Digest: sha256:fef6485ba433bdc568059bbff157bd605d1462c603c485a821461851de2a132f
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:f01b91323fbe89c1b1914f45f43e9f606b0feefef0401e25f0a7126141e4b3e3
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
===> ANALYZING
Previous image with name "sample" not found
===> DETECTING
4 of 5 buildpacks participating
google.java.runtime    0.9.1
google.java.gradle     0.9.0
google.java.entrypoint 0.9.0
google.utils.label     0.0.2
===> RESTORING
===> BUILDING
=== Java - Runtime (google.java.runtime@0.9.1) ===
Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
2023/03/13 16:05:52 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Installing  v11.0.18+10.
2023/03/13 16:05:53 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.18_10.tar.gz
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
=== Java - Gradle (google.java.gradle@0.9.0) ===
--------------------------------------------------------------------------------
Running "./gradlew clean assemble -x test --build-cache --quiet"
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%
```

If I run `./gradlew run` the server starts as expected.

What am I doing wrong? The sample java project from https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-java-gradle works just fine, so I don't think there's an issue with my local set-up.

I also tried running on Google Cloud Build and got slightly more information:

```
[builder] Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
[builder] ...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%
[builder] Done "./gradlew clean assemble -x test --build-cache --quiet" (2m23.226743201s)
[builder] === Java - Entrypoint (google.java.entrypoint@0.9.0) ===
[builder] Failure: (ID: 838926df) did not find any jar files with a Main-Class manifest entry
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://cloud.google.com/docs/buildpacks/overview
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
```

I don't know where it's trying to find the main class. The `application` plugin should be taking care of this with the

```
application {
    mainClass.set("com.sample.MainKt")
}
```
section.

**Comment by bdbrownell** [comment]
Not sure if related but I have been experiencing a similar bug trying to build a Nodejs application that had previously worked. Coincides with the newest NodeJS buildpack release from the 7th of March. I was able to build it fine on March 7th, have not had any success since. 

I can open a separate incident if needed.

**Comment by davidals** [comment]
Here's a verbose output in case it helps: https://gist.github.com/davidals/3baac295c3d289dc741c956526dddd22

**Comment by davidals** [comment]
Yeah, doesn't seem that I'm at fault.

Just tried running pack on the demo repo: https://github.com/GoogleCloudPlatform/kotlin-samples/tree/main/run/http4k-hello-world

And got the same state

**Comment by davidals** [comment]
I also tried on this demo repo: https://github.com/GoogleCloudPlatform/kotlin-samples/tree/main/run/http4k-hello-world

And this is the output:

```
 pack build --builder=gcr.io/buildpacks/builder:v1 http4k-hello-world 
v1: Pulling from buildpacks/builder
Digest: sha256:fef6485ba433bdc568059bbff157bd605d1462c603c485a821461851de2a132f
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:f01b91323fbe89c1b1914f45f43e9f606b0feefef0401e25f0a7126141e4b3e3
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
===> ANALYZING
Previous image with name "http4k-hello-world" not found
===> DETECTING
4 of 5 buildpacks participating
google.java.runtime      0.9.1
google.java.gradle       0.9.0
google.config.entrypoint 0.9.0
google.utils.label       0.0.2
===> RESTORING
Skipping buildpack layer analysis
===> BUILDING
=== Java - Runtime (google.java.runtime@0.9.1) ===
Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
2023/03/14 14:49:06 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Installing  v11.0.18+10.
2023/03/14 14:49:06 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.18_10.tar.gz
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
=== Java - Gradle (google.java.gradle@0.9.0) ===
--------------------------------------------------------------------------------
Running "./gradlew clean assemble -x test --build-cache --quiet"
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%
```

**Comment by kritkasahni-google** [comment]
@davidals I have tried building kotlin sample app and turns out you will need to add Procfile similar to java-sample code you linked above https://github.com/GoogleCloudPlatform/buildpack-samples/blob/master/sample-java-gradle/Procfile. I was seeing same error - "Failure: (ID: 838926df) did not find any jar files with a Main-Class manifest entry" - until I added Procfile to the project.

Also, don't worry about getting stuck after "Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip" -> it just takes a bit to download gradle distro and happened in my system also.

**Comment by kritkasahni-google** [comment]
Logs after I added Procfile 
```
===> DETECTING
4 of 5 buildpacks participating
google.java.runtime      0.9.1
google.java.gradle       0.9.0
google.config.entrypoint 0.9.0
google.utils.label       0.0.2
===> RESTORING
===> BUILDING
=== Java - Runtime (google.java.runtime@0.9.1) ===
Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
2023/03/14 04:59:13 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Installing  v11.0.18+10.
2023/03/14 04:59:13 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.18_10.tar.gz
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
=== Java - Gradle (google.java.gradle@0.9.0) ===
--------------------------------------------------------------------------------
Running "./gradlew clean assemble -x test --build-cache --quiet"
Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%
Done "./gradlew clean assemble -x test --build-cache --quiet" (1m9.018215402s)
=== Config - Entrypoint (google.config.entrypoint@0.9.0) ===
Using entrypoint from Procfile: java -cp build/libs/demo.jar demo.AppKt
=== Utils - Label Image (google.utils.label@0.0.2) ===_


```

**Comment by davidals** [comment]
I remember trying to add one like the one from sample-java-gradle. 

This is it's contents:

```
web: java -cp build/libs/backend-1.0-SNAPSHOT.jar com.sample.MainKt
```

The file is there, but it's still failing :/

Also, does this means that this is wrong? https://github.com/GoogleCloudPlatform/kotlin-samples/blob/main/run/http4k-hello-world/Procfile


If you point me in the right direction I can add a PR for improving the documentation on this since this page: https://cloud.google.com/docs/buildpacks/overview implies it is optional for everything except Python.

**Comment by davidals** [comment]
First of all thanks @kritkasahni-google  ! It worked for me when running on Cloud Build using `gcloud builds submit --pack image=...`

So, this is interesting, while it works there, it hangs right after finishing downloading gradlew:

```
Running "./gradlew clean assemble -x test --build-cache --quiet"
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%
```

I ran this on one terminal and Cloud build on another at the same time.
It's been 10 minutes since the cloud build finished and the local one is still on that log message...

**Comment by bdbrownell** [comment]
I received that BOM debug warning in my build step as well, the flag that fixed it for me was to add '--no-cache' to the deploy command. I see you have used --build-cache in your solution as well - Might be something wrong with the cached version of the buildpack?

**Comment by kritkasahni-google** [comment]
@davidals  https://github.com/GoogleCloudPlatform/kotlin-samples/blob/main/run/http4k-hello-world/Procfile works as it is. Look at logs below:-


`http4k-hello-world git:(main) pack build --builder=gcr.io/buildpacks/builder:v1 http4k-hello-world
v1: Pulling from buildpacks/builder
Digest: sha256:fef6485ba433bdc568059bbff157bd605d1462c603c485a821461851de2a132f
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:f01b91323fbe89c1b1914f45f43e9f606b0feefef0401e25f0a7126141e4b3e3
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
===> ANALYZING
Previous image with name "http4k-hello-world" not found
===> DETECTING
4 of 5 buildpacks participating
google.java.runtime      0.9.1
google.java.gradle       0.9.0
google.config.entrypoint 0.9.0
google.utils.label       0.0.2
===> RESTORING
===> BUILDING
=== Java - Runtime (google.java.runtime@0.9.1) ===
Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
2023/03/14 17:46:43 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Installing  v11.0.18+10.
2023/03/14 17:46:43 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.18_10.tar.gz
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
=== Java - Gradle (google.java.gradle@0.9.0) ===
--------------------------------------------------------------------------------
Running "./gradlew clean assemble -x test --build-cache --quiet"
Downloading https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
...........10%............20%...........30%............40%...........50%............60%...........70%............80%...........90%............100%
Done "./gradlew clean assemble -x test --build-cache --quiet" (1m6.948813703s)
=== Config - Entrypoint (google.config.entrypoint@0.9.0) ===
Using entrypoint from Procfile: build/install/hello-kotlin-http4k/bin/hello-kotlin-http4k
=== Utils - Label Image (google.utils.label@0.0.2) ===
===> EXPORTING
Adding layer 'google.java.runtime:java'
Adding layer 'buildpacksio/lifecycle:launch.sbom'
Adding 1/1 app layer(s)
Adding layer 'buildpacksio/lifecycle:launcher'
Adding layer 'buildpacksio/lifecycle:config'
Adding layer 'buildpacksio/lifecycle:process-types'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
Setting default process type 'web'
Saving http4k-hello-world...
*** Images (91456bd99cdd):
      http4k-hello-world
Adding cache layer 'google.java.runtime:java'
Adding cache layer 'google.java.gradle:cache'
Successfully built image http4k-hello-world`

**Comment by kritkasahni-google** [comment]
Again I would remind you it won't hang it just takes a min or two to install gradle distro during build.

**Comment by davidals** [comment]
> Again I would remind you it won't hang it just takes a min or two to install gradle distro during build.

Yeah, it's not hanging on downloading gradle itself, but that's the last message I see before it gets stuck forever.

I'll do a clean reinstall of pack and docker.
Now it works with both the sample from kotlinsamples and the ones from java-gradle-sample.

**Comment by davidals** [comment]
Did the clean re-install.

Still not finishing a run.
Any way to get more logs than the verbose flag?

**Comment by kritkasahni-google** [comment]
I am not able to reproduce this issue. When I try pack build locally it works without any errors.
