### ISSUE TITLE
Composer 2.2 support

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#288]
In order to support Laravel 10, buildpack would need to use Composer 2.2 instead of 2.1. Laravel is the most popular framework in the PHP world, and support of the latest version should be a high priority.

Ref.: https://github.com/laravel/framework/commit/88b703b78aa61f37944a0b19fe65d75437a9b0a6

**Comment by jama22** [comment]
@sl0wik looks like the feature is now live in the PHP buildpacks. You should be able to set Composer 2.2 by adding the `GOOGLE_COMPOSER_VERSION` environment variable (see https://cloud.google.com/docs/buildpacks/php#configure_composer)

Let us know if that works

**Comment by sl0wik** [comment]
On App Engine this snippet must be added to `app.yaml`:
```
build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.5.8
```
