### ISSUE TITLE
Go vulnerability issue detected in buildpacksio/lifecycle:0.16.0

### ISSUE THREAD

**Issue by jpreynat** [GoogleCloudPlatform/buildpacks#298]
Hi 👋 

Our vulnerability scanner detected a critical security issue in our Node code deployed on Cloud Run via the `gcloud run deploy` command using the default buildpacks.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/7927876/236482931-00fddff3-4736-403f-b751-76dcea9eb47e.png">

After investigating, I found that this is a file located in the `buildpacksio/lifecycle:0.16.0` container that is pulled during the build of our Cloud Run image.

This is problematic for us as we need to close this security issue ASAP.
The fix would be to upgrade to go 1.19.8, which is available in `buildpacksio/lifecycle:0.17.0-pre.1`:
https://github.com/buildpacks/lifecycle/releases/tag/v0.17.0-pre.1

 Would you consider updating this image?
If not, are there any workarounds to maybe use the new `google-22` pack without the hassle of first running the build then using the image in the `gcloud run deploy` command?

Thanks!

**Comment by jama22** [comment]
Thanks for reporting the issue @jpreynat . We're working with the cloud native buildpacks (CNB) team to get a patch released using updated go binaries (see linked issue). We're discussing this fix with them on their slack and we'll cut a new builder as soon as we get the update from the CNB team.

**Comment by jpreynat** [comment]
Thanks for the quick answer and taking care of it @jama22 👍

**Comment by jama22** [comment]
Update, we've coordinated with CNB team to verify the fix in their [0.16.3 release ](https://github.com/buildpacks/lifecycle/releases/tag/v0.16.3). We'll be able to take on that patch and start testing for a fix. Target early next week for release.

**Comment by matthewrobertson** [comment]
This should be all fixed now. I tested out a `gcloud run deploy` with default settings and verified that an Artifact Registry scan of the app image is reporting 0 fixable CVEs. Thanks for bringing this to our attention @jpreynat!

**Comment by jpreynat** [comment]
Thanks for the very quick fix and for letting me know @jama22 and @matthewrobertson!
