### ISSUE TITLE
Update Buildpacks documentation with PHP Build  Environment variables

### ISSUE THREAD

**Issue by jama22** [GoogleCloudPlatform/buildpacks#299]
**Is your feature request related to a problem? Please describe.**
Somewhat related to #288, there are build-time environment variables that are supported by the PHP buildpacks that aren't documented in https://cloud.google.com/docs/buildpacks/overview 

**Describe the solution you'd like**
@kennethye1 linked out to documentation in [App Engine](https://cloud.google.com/appengine/docs/standard/testing-and-deploying-your-app?tab=php#build-env-vars), and those details could be moved over to a new language-specific configuration page for PHP

**Comment by kennethye1** [comment]
https://cloud.google.com/docs/buildpacks/php
