### ISSUE TITLE
PHP composer should accessible inside container

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#306]
I'm using buildpacks to build my local environment to guarantee consistency with production environment. In general its working fine but having no access to `composer` forcing developers to have composer installed locally using the same version as container they are working with. If `composer` is accessible inside container it would allow to update composer.json file directly from container using something like `/cnb/lifecycle/launcher composer update`.

PHP composer should be available under `/layers/google.php.composer/`, and it should be possible to run it using `/cnb/lifecycle/launcher composer` if possible.

**Comment by iamacarpet** [comment]
We have experienced the same problem.

Initially, the buildpacks (used by App Engine) used to have `composer` pre-installed.

Then it switched to being installed at runtime, and you could do this to install it:

```
(cd /cnb/buildpacks/google.php.composer-install/*; ./bin/build /builder 0 0)
ln -s /builder/composer/bin/composer /usr/local/bin/composer
```

however, that stopped working a while ago as well.

We've now been forced to do this:

![image](https://github.com/GoogleCloudPlatform/buildpacks/assets/1333857/c6618ea5-88ee-4552-8cf5-a69f01607cf5)

**Comment by sl0wik** [comment]
I found a solution without buildpack update.

Add to your `composer.json`:
```
    "require": {
        ...
        "composer/composer": "^2.1",
    }
```

Use `/cnb/lifecycle/launcher php vendor/bin/composer`.
