### ISSUE TITLE
it does not support .env files?

### ISSUE THREAD

**Issue by Divyashet66** [GoogleCloudPlatform/buildpacks#312]
I tried to build nodejs  image using this buildpack, but whatever I have stored in .env file is not getting reflected, so the image is not running properly, so what can I do in this case?

**Comment by matthewrobertson** [comment]
Hi @Divyashet66, please see [this page of our documentation](https://cloud.google.com/docs/buildpacks/set-environment-variables) that describes a number of options for setting environment variables.

**Comment by jama22** [comment]
@Divyashet66 hope the docs were able to help you. Feel free to open a new [Discussion](https://github.com/GoogleCloudPlatform/buildpacks/discussions) if you're having trouble setting environment variables

**Comment by GooGam** [comment]
Hi everyone, I'm experiencing the same issue, but I'm following the command from [this documentation ](https://cloud.google.com/docs/buildpacks/set-environment-variables). I'm trying to use buildpack to wrap a cloud function with some env variables since Function Frameworks do not support this.
Here's the command I used:
```
 pack build my-cloud-function-name\
     --builder gcr.io/buildpacks/builder:v1 \
     --env GOOGLE_FUNCTION_SIGNATURE_TYPE=http \
     --env GOOGLE_FUNCTION_TARGET=mycloudfunctionname \
     --env _MY_VAR=true
```
I tried to retrieve the variable by using process.env._MY_VAR, but it is undefined.

**Comment by jama22** [comment]
Ah, so I think what's confusing here is that the `pack --env` flag only sets environment variables at build time. I couldn't find any reference in the buildpack specification doesn't let you set run-time environment variables. I did find this discussion thread about it though https://github.com/buildpacks/community/discussions/61

If you're using Cloud Functions directly, you should be able to set the runtime variable using the instructions here https://cloud.google.com/functions/docs/configuring/env-var

If you're building the image with `pack` and directly deploying on Cloud Run, you can set the run-time environment variable using the instructions here https://cloud.google.com/run/docs/configuring/services/environment-variables

**Comment by GooGam** [comment]
Aha, I see the point. I'm actually using buildpack to build the image and using docker to run the image just for testing cloud function locally. Thanks @jama22 for your clarification, I figure out that I could use docker to pass in runtime variables.
