### ISSUE TITLE
google.java.maven@0.9.0 failure

### ISSUE THREAD

**Issue by juturumanoj** [GoogleCloudPlatform/buildpacks#316]
**Describe the bug**
i am using a gcloud run deploy with source as code. it fails build step with below issue
Step #1: === Java - Maven (google.java.maven@0.9.0) ===
Step #1: Installing Maven v3.6.3
Step #1: Failure: (ID: 86a1af80) Maven version 3.6.3 does not exist at https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz (status 404).

If you have a general question about how to use buildpacks, we encourage you to open a [discussion topic instead](https://github.com/GoogleCloudPlatform/buildpacks/discussions)

**Additional context**
How are you using GCP buildpacks?
Cloud Run

**Did this used to work?**
*Yes*
Was this working before? When did you start noticing these errors?
It was working till 8-June-2023.. and started failing June 9

**What language is your project primarily written in?**
*(Java)*

**Steps To Reproduce**
1.  `gcloud run --project="project-first" deploy test-source --source .`

**Expected behavior**
Build and deploy the service to cloud run

**Actual behavior**
Build failed

If applicable, add screenshots / logs / error messages
Step #1: ===> DETECTING
Step #1: 4 of 5 buildpacks participating
Step #1: google.java.runtime      0.9.1
Step #1: google.java.maven        0.9.0
Step #1: google.java.entrypoint   0.9.0
Step #1: google.utils.label-image 0.0.2
Step #1: ===> RESTORING
Step #1: ===> BUILDING
Step #1: === Java - Runtime (google.java.runtime@0.9.1) ===
Step #1: Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
Step #1: 2023/06/09 08:05:29 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Step #1: Installing  v11.0.19+7.
Step #1: 2023/06/09 08:05:29 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.19_7.tar.gz
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: === Java - Maven (google.java.maven@0.9.0) ===
Step #1: Installing Maven v3.6.3
Step #1: Failure: (ID: 86a1af80) Maven version 3.6.3 does not exist at https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz (status 404).

**Comment by kappratiksha** [comment]
We are working on updating the maven version to the latest and that should fix the issue with the maven buildpack.

**Comment by juturumanoj** [comment]
> We are working on updating the maven version to the latest and that should fix the issue with the maven buildpack.

Thank you for the reply @kappratiksha : Any ETA on this? Our customer critical production deploys are blocked. If any other alternative steps of the same, please provide steps

**Comment by kappratiksha** [comment]
@juturumanoj  The issue has been fixed now. Can you try redeploying again.

**Comment by juturumanoj** [comment]
Working now.. thank you..
