### ISSUE TITLE
google.java.maven@0.9.0 - failure

### ISSUE THREAD

**Issue by juturumanoj** [GoogleCloudPlatform/buildpacks#318]
**Describe the bug**
i am using a gcloud run deploy with source as code. it fails build step with below issue
Step #1: === Java - Maven (google.java.maven@0.9.0) ===
Step #1: Installing Maven v3.9.2
Step #1: Failure: (ID: 1d1e6a05) Maven version 3.9.2 does not exist at https://downloads.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz (status 404).

If you have a general question about how to use buildpacks, we encourage you to open a [discussion topic instead](https://github.com/GoogleCloudPlatform/buildpacks/discussions)

**Additional context**
How are you using GCP buildpacks?
- [ ] `pack` and the `gcr.io/buildpacks/builder`
- [ ] Cloud Functions
- [X] Cloud Run
- [ ] Cloud Build
- [ ] App Engine Standard
- [ ] App Engine Flex

**Did this used to work?**
Yes
Was this working before? When did you start noticing these errors?
 It was working till 26th June.

**What language is your project primarily written in?**
Java

**Steps To Reproduce**
1.  ` gcloud run --project="project-first" deploy test-source --source ..`

**Expected behavior**
 Build and deploy the service to cloud run

**Actual behavior**
What actually happened?
 Build failed

If applicable, add screenshots / logs / error messages
Step #1: 4 of 5 buildpacks participating
Step #1: google.java.runtime      0.9.1
Step #1: google.java.maven        0.9.0
Step #1: google.java.entrypoint   0.9.0
Step #1: google.utils.label-image 0.0.2
Step #1: ===> RESTORING
Step #1: ===> BUILDING
Step #1: === Java - Runtime (google.java.runtime@0.9.1) ===
Step #1: Using latest Java 11 runtime version. You can specify a different version with GOOGLE_RUNTIME_VERSION: https://github.com/GoogleCloudPlatform/buildpacks#configuration
Step #1: 2023/06/26 13:14:34 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/version.json
Step #1: Installing  v11.0.19+7.
Step #1: 2023/06/26 13:14:34 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/openjdk/openjdk-11.0.19_7.tar.gz
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: Warning: BOM table is deprecated in this buildpack api version, though it remains supported for backwards compatibility. Buildpack authors should write BOM information to <layer>.sbom.<ext>, launch.sbom.<ext>, or build.sbom.<ext>.
Step #1: === Java - Maven (google.java.maven@0.9.0) ===
Step #1: Installing Maven v3.9.2
Step #1: Failure: (ID: 1d1e6a05) Maven version 3.9.2 does not exist at https://downloads.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz (status 404).

**Comment by smsohan** [comment]
Looks like the download link broke for Maven. We're looking at this issue.

**Comment by kennethye1** [comment]
We're fixing the issue right now and working on a release.
