### ISSUE TITLE
PHP extensions curl, zlib and gd missing in builder:google-22

### ISSUE THREAD

**Issue by JohandeGraaf** [GoogleCloudPlatform/buildpacks#325]
**Describe the bug**

curl, zlib and gd PHP extensions seem to be missing in [builder:google-22](https://gcr.io/buildpacks/builder:google-22). It used to work in [builder:v1](https://gcr.io/buildpacks/builder:v1)

composer.json:
```
{
  "require": {
    "php": "8.2.*",
    "ext-json": "*",
    "ext-curl": "*",
    "ext-openssl": "*",
    "ext-zlib": "*",
    "ext-pdo": "*",
    "ext-gd": "*",
    "ext-mbstring": "*"
  }
}
```

**Additional context**
How are you using GCP buildpacks?
- [x] `pack` and the `gcr.io/buildpacks/builder`

**Did this used to work?**
Yes, it used to work in builder:v1.

**What language is your project primarily written in?**
PHP 8.2

**Steps To Reproduce**
1.  `gcloud --quiet --verbosity=error builds submit --pack image=<IMAGE>,builder=gcr.io/buildpacks/builder:google-22 <FOLDER>`

**Expected behavior**
The curl / gd / zlib extensions to be enabled/installed

**Actual behavior**
```
[builder] Your lock file does not contain a compatible set of packages. Please run composer update.
[builder]
[builder]   Problem 1
[builder]     - Root composer.json requires PHP extension ext-curl * but it is missing from your system. Install or enable PHP's curl extension.
[builder]   Problem 2
[builder]     - Root composer.json requires PHP extension ext-zlib * but it is missing from your system. Install or enable PHP's zlib extension.
[builder]   Problem 3
[builder]     - Root composer.json requires PHP extension ext-gd * but it is missing from your system. Install or enable PHP's gd extension.
```

**Comment by sriram-mahavadi** [comment]
We have actually decided to add the extensions back into the google-22 builder. Please feel free to try and use it. Also, reopen the issue if you get any questions.
