### ISSUE TITLE
Support "k8schain" authentication option

### ISSUE THREAD

**Issue by mattmoor** [GoogleCloudPlatform/buildpacks#33]
I can't run this on Tekton on GKE (or EKS, or AKS) today without configuring auth *the hard way* because there isn't a k8schain option for using the ambient workload auth available thru http://metadata et al.

See: https://github.com/google/go-containerregistry/tree/master/pkg/authn/k8schain

**Comment by lukasberger** [comment]
Are you using the official tekton [template](https://github.com/tektoncd/catalog/tree/master/buildpacks), pack, or invoking the builder directly?

If it's the lifecycle steps that are failing, I think this would be a FR for [lifecycle](https://github.com/buildpacks/lifecycle). Our buildpacks rely on the environment already being configured.

**Comment by mattmoor** [comment]
I talked to some of the buildpacks folks directly, and I think that they are going to probably pull this into the default keychain resolution logic.

We can close this for now.

**Comment by mattmoor** [comment]
For posterity, I was using a taskrun derived from the catalog task definition, but not literally that task.

The task definition just seems outright broken as `-helpers` was removed at some point.
