### ISSUE TITLE
google-22 buildpack builder is unable to build node application from source with dependency that requires "node-gyp rebuild"

### ISSUE THREAD

**Issue by dankuchler** [GoogleCloudPlatform/buildpacks#335]
We have a node application that we are building into a container from source in cloudbuild using pack and the gcr.io/buildpacks/builder.  This process was working fine with the v1 version of the buildpack builder.  In the google-22 verison of the buildpack builder the build is failing during the builders execution of "npm ci --quiet (NODE_ENV=production)"

One of the npm dependencies of the node application (lz4) requires a "node-gyp rebuild" during the npm install.  During the "node-gyp rebuild" step in the google-22 buildpack builder node-gyp is unable to locate a python3 installation and the buildpack builder fails.

[builder] Installing application dependencies.
[builder] --------------------------------------------------------------------------------
[builder] Running "npm ci --quiet (NODE_ENV=production)"

[builder] npm ERR! code 1
[builder] npm ERR! path /workspace/node_modules/lz4
[builder] npm ERR! command failed
[builder] npm ERR! command sh -c -- node-gyp rebuild
[builder] npm ERR! gyp ERR! find Python
[builder] npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
[builder] npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
[builder] npm ERR! gyp ERR! find Python checking if "python3" can be used
[builder] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
[builder] npm ERR! gyp ERR! find Python checking if "python" can be used
[builder] npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error

It appears the google-22 buildpack builder is failing to identify the need for a python installation to be available as part of the npm / node-gyp build requirements - however we do not have this issue with the v1 buildpack builder.

The resulting container built through cloudbuild using pack and the gcr.io/buildpacks/builder is being deployed through cloud run.
**Additional context**
How are you using GCP buildpacks?
- [X] `pack` and the `gcr.io/buildpacks/builder`
- [ ] Cloud Functions
- [X] Cloud Run
- [X] Cloud Build
- [ ] App Engine Standard
- [ ] App Engine Flex

**Did this used to work?**
Yes

This issue began at the end of June when the default "latest" version of the buildpack builder was upgraded from v1 to google-22.  using the v1 version of the builder continues to work - but due to the end of support for node 16 coming in September we need to upgrade to node 18 or node 20 which are supported by the google-22 version of the buildpack.

**What language is your project primarily written in?**

Node.js

** Steps to reproduce
1. Create a nodejs project that requires an npm dependency with a "node-gyp rebuild" step such as the npm package lz4
2. pack build <image> --builder=gcr.io/buildpacks/builder:google-22 --descriptor=project.toml --publish

**Comment by jama22** [comment]
@dankuchler i'll try to repro. Out of curiosity is the version of `l4z` pinned to a specific version?

**Comment by sriram-mahavadi** [comment]
Updated to include python3 in google-22 builder image. 
Please retry building with `builder:google-22` version and let us know if you find any further issues. Thank you.

**Comment by smsohan** [comment]
https://github.com/GoogleCloudPlatform/buildpacks/commit/bb26e8a22ead4b5ac2aceb76e6453dcdf1201638

**Comment by jama22** [comment]
@dankuchler  to add more context here, I managed to repro this quite easily, thanks again for the detailed report.

The root cause is that we dropped the `python3` package in the Ubuntu 22  builder image [package list](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/stacks/google_22/build-packages.txt). 

As @sriram-mahavadi and @smsohan mentioned, we've decided to re-introduce the `python3` package into the builder image and unblock folks.  `npm-gyp` seems to be a pretty common package and it may be the case that some linux tooling might rely on `python3` as well. 

The fix should show up in the builder, so you can retry at your convenience. I'm also reopening the issue so you can reply, and then we'll close once you let us know you can build your app on `ubuntu-22`
