### ISSUE TITLE
[builder] Failure: (ID: 7eb4de08) Failed to run /bin/build: for Python, provide a main.py file or set an entrypoint with "GOOGLE_ENTRYPOINT" env var or by creating a "Procfile" file

### ISSUE THREAD

**Issue by funingg** [GoogleCloudPlatform/buildpacks#337]
Hi,

I am justing using a cloud build to build a simple node.js cloud run but ran into a python dependency issue.

Build log here: https://pantheon.corp.google.com/cloud-build/builds;region=global/e5a9f57d-3eef-4d1d-b52a-b1ef42ac51d5

**Comment by jama22** [comment]
We try to keep the github issues free of techncial support type questions. Closing this issue.
