### ISSUE TITLE
Java Gradle and Maven buildpacks should support build arguments

### ISSUE THREAD

**Issue by jama22** [GoogleCloudPlatform/buildpacks#338]
**Is your feature request related to a problem? Please describe.**
Currently, the Gradle and Maven buildpacks have hardcoded build arguments:
* Gradle runs https://github.com/GoogleCloudPlatform/buildpacks/blob/d72f286edd1101b2e00630a15928123fd0261a79/cmd/java/gradle/main.go#L86
* Maven runs https://github.com/GoogleCloudPlatform/buildpacks/blob/d72f286edd1101b2e00630a15928123fd0261a79/cmd/java/maven/main.go#L95

However, there are cases where projects want to override the build arguments to suit their needs, such as adding flags for modifying logging, stacktraces, etc. 

**Describe the solution you'd like**
Similar to how other buildpack providers do this, it would be nice if the Gradle and Maven buildpacks had a way to let users specify the build arguments. For example:

`GOOGLE_GRADLE_BUILD_ARGS="clean assemble -x test --build-cache"`
`GOOGLE_MAVEN_BUILD_ARGS=""clean package --batch-mode -DskipTests -Dhttp.keepAlive=false"`

**Describe alternatives you've considered**
There could be a general environment variable, but i would assume there might becases where projects use a combination of Gradle and Maven

**Comment by jama22** [comment]
Some additional context, there is an existing `GOOGLE_BUILD_ARGS` environment variable that exists today but that only *appends* the values to the _existing_ build command for the participating buildpack. So if you're looking to just append a few additional commands this works, but you can't completely replace it. 

We wouldn't be able to change the behavior of this environment variable as it would constitute a breaking change, so this is why I'm proposing two new variables.

Alternatively it could be something like `GOOGLE_BUILD_ARGS_OVERRIDE` or something

**Comment by skakauridze-clgx** [comment]
Hey @jama22 just checking if there is any update on this?

Thanks
Shalva

**Comment by kappratiksha** [comment]
We have started working on this and will update once the changes are in.

**Comment by kappratiksha** [comment]
Hi @skakauridze-clgx, the changes for this got checked in. You can try using GOOGLE_MAVEN_BUILD_ARGS and/or GOOGLE_GRADLE_BUILD_ARGS now. Let me know if you run into any issues. Thanks

**Comment by kappratiksha** [comment]
The documentation for this change can be found here : https://cloud.google.com/docs/buildpacks/service-specific-configs.
