### ISSUE TITLE
Container Registry Deprecation

### ISSUE THREAD

**Issue by j-windsor** [GoogleCloudPlatform/buildpacks#350]
Per https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation, Container Registry is deprecated and images must be migrated to Artifact Registry. My team currently has a customer impacting issue making buildpacks unusable in our scenarios due to an issue that will not be fixed in Container Registry.

Is there a timeline to move gcr.io/buildpacks to Artifact Registry?

**Comment by jama22** [comment]
@j-windsor this is an open source issue tracker. Edited your post to remove the link to internal bug tracker. 

We're tracking the Container Registry deprecation and in the process of moving our images to avoid getting impacted by the deprecation. Don't have a timeline to share right now, but we're aiming to move it soon.
