### ISSUE TITLE
build failures on PHP + builder:google-22 + gRPC

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#361]
Yesterday (November 1st 2023) I started receiving errors from some unchanged CI/CD pipelines. It looks like `builder:latest` is failing to build PHP packages using gRPC.

Steps to reproduce https://github.com/sl0wik/buildpacks-grpc-issue

**Comment by smsohan** [comment]
While we take a look at it, please use builder:v1.

**Comment by sriram-mahavadi** [comment]
Presently there is a migration to have `gcloud builds pack` or `gcloud run deploy --source` to use the `builder:latest` instead of `builder:v1`. I have stopped this migration until this issue is resolved. Presently i am working on the next steps for fixing this issue. Thank you.

**Comment by sriram-mahavadi** [comment]
This issue is now resolved as I have added all the extensions to `builder:latest` as necessary. Please feel free to reopen the issue if you have any further questions.
