### ISSUE TITLE
gcloud app deploy - Issue with a post install script in my package.json

### ISSUE THREAD

**Issue by glorio-loopstudio** [GoogleCloudPlatform/buildpacks#370]
**Describe the bug**
I am actually trying to deploy my nest.js app to GC app engine.
When I run the following command:

`gcloud app deploy`

The following error come to me:
<img width="837" alt="Captura de pantalla 2023-12-08 a la(s) 18 27 48" src="https://github.com/GoogleCloudPlatform/buildpacks/assets/96254656/683fae21-95fa-4008-97b1-187b44585085">

The issue seems to be in my `package.json` because when I comment the following script, the command to deploy the app works without any problem. Here is my script that is causing these to fails:

`"postinstall": "git config core.hooksPath ./git-hooks"`

**Comment by kennethye1** [comment]
App Engine is only given the source code. It would not know that it's in a git directory or not.
