### ISSUE TITLE
Invalid default if `script.start`  doesn't exist

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpacks#375]
I can read:  If `scripts.start` is not set, the buildpack will run `npm start`.

This is an incorrect default behavior: If `scripts.start` is not set, `npm start` will always fail with `Missing script: "start"` 

I'd expect instead to default to `node index.js`

CC @jama22

**Comment by matthewrobertson** [comment]
This is a reasonable default.
