### ISSUE TITLE
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51

### ISSUE THREAD

**Issue by gsolorza** [GoogleCloudPlatform/buildpacks#376]
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51

**Comment by gsolorza** [comment]
This is while trying to test a python cloud function

**Comment by jama22** [comment]
@gsolorza can you give some more information and steps to reproduce? How are you building the application? locally with `pack` ? with Cloud Build?

**Comment by gsolorza** [comment]
Hi James,

I was testing cloud functions.
When I try to test the function before deploying it gives me the following
error. Apparently is complaining about the version of Python (which I am
selecting from a dropdown).
If I try with an older version of Python, this does not happen.

[image: image.png]



*George SolórzanoNetwork Consulting Engineer*
*CCIE # 45634 (SP)*

*+56 958164514 *

**Comment by jama22** [comment]
Thanks for the clarification! I managed to reproduce it on my side. I'll dig into it.

In general, this issue tracker shouldn't be used to report GCP-specific issues, but in this case I'll allow it 😄

**Comment by jama22** [comment]
Fix just went live earlier today.

**Comment by gsolorza** [comment]
Awesome, thanks !!

**Comment by gittymadman** [comment]
I'm still getting this error. Can anyone help
