### ISSUE TITLE
 failed to build: (error ID: 14f2a5b3)

### ISSUE THREAD

**Issue by pattopilco** [GoogleCloudPlatform/buildpacks#380]
executing command "./gradlew clean assemble -x test --build-cache --quiet": fork/exec ./gradlew: permission denied

**Comment by jama22** [comment]
Hey @pattopilco can you please provide more details? This is not enough information for us to understand your issue (e.g. is this related to buildpacks or a project misconfiguration). The bug template was created to help us understand incoming issues so we can better serve the community.

**Comment by matthewrobertson** [comment]
sounds like you have included the gradle wrapper in the root of your project but the unix file permissions are too strict for the CNB user to execute it. You probably need to run something like `chmod a+x ./gradlew`

**Comment by matthewrobertson** [comment]
I think this might have been an issue with windows line endings which I fixed in this commit: https://github.com/GoogleCloudPlatform/buildpacks/commit/e48ab7dcd51a873ba11089e6f5f8c774163c99df
