### ISSUE TITLE
Provide wget in gcr.io/buildpacks/builder

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/buildpacks#39]
I built a container image registry service that fetches source from GitHub and builds and serves images just-in-time, at pull-time: https://kontain.me/

One of the ways it builds is using buildpacks:

```
docker pull buildpack.kontain.me/buildpack/sample-java-app:25b3fcb
```

Currently it's hard-coded to use `packs/samples:v3alpha2` and I was looking into switching it to `gcr.io/buildpacks/builder` instead.

Unfortunately, the way the service works, [it relies on `wget` being installed in the builder image](https://github.com/ImJasonH/kontain.me/blob/7f6572d0a25212ea42dd6d3547173111f54c8f44/cmd/buildpack/main.go#L247), which happens to be the case for `packs/samples:v3alpha2`, but isn't the case for this builder.

Is there any way I can convince you to install `wget`, so this service can port over?

**Comment by lukasberger** [comment]
> I was looking into switching it to gcr.io/buildpacks/builder instead.

That'd be amazing!

> Is there any way I can convince you to install wget, so this service can port over?

I have a counter proposal, since we already have `curl` installed, could that line be switched to `curl -fsSL % | ...` instead? I think that should be functionally equivalent.

**Comment by ImJasonH** [comment]
@lukasberger Perfect! I've got it detecting and building now, but `/lifecycle/exporter` now fails because creds aren't being found, even though the Cloud Run app should be authorizing as the service account.

```
failed to export: failed to write image to the following tags: [gcr.io/kontainme/built-9790736: GET https://gcr.io/v2/token?scope=repository%3Akontainme%2Fbuilt-9790736%3Apush%2Cpull&service=gcr.io: UNAUTHORIZED: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication]
...
ERROR: Running "/lifecycle/exporter -layers=/tmp/598153606 -app=/tmp/390773763/sample-go -image=packs/run:v3alpha2 -group=/tmp/598153606/group.toml gcr.io/kontainme/built-9790736": exit status 1
```

Is the gcr cred helper available and configured in the image? This worked without any special work with `packs/samples:v3alpha2`, where `/lifecycle/exporter` accepted a `-helpers=true` flag. Is there any flag like that for this builder's `/lifecycle/exporter`?

**Comment by lukasberger** [comment]
Ah, it looks like it was removed in buildpacks/lifecycle#121 ([RFC](https://github.com/buildpacks/rfcs/blob/master/text/0028-remove-cred-helpers.md)). I think you mind need to add the GCR credential helper to .docker/config.json [manually](https://github.com/GoogleCloudPlatform/docker-credential-gcr#manual-docker-client-configuration).

**Comment by ImJasonH** [comment]
Looks like it's not included in the image?

```
failed to get previous image: error getting credentials - err: exec: "docker-credential-gcr": executable file not found in $PATH, out: ``
```

**Comment by lukasberger** [comment]
Should that be in the image or on the machine running the image? `pack` for example seems to use the host's credentials helper.

**Comment by ImJasonH** [comment]
> Should that be in the image or on the machine running the image? `pack` for example seems to use the host's credentials helper.

In this case, I'm expecting it to be in the builder image. The way `buildpack.kontain.me` works is that it's a Cloud Run app, running a container image that is effectively `FROM gcr.io/buildpacks/builder`, with a little Go server in front of it that serves the Docker registry API. When it comes time to build, it calls the `/lifecycle/detect`, etc., binaries present in the image. When it goes to push, it expected to find the GCR cred helper to help it do that, and that worked when it was `FROM pack/samples:v3alpha2`.

[I got it working though](https://github.com/ImJasonH/kontain.me/commit/2a0494f5deeb2ce744867eeb9283bd4323c65c5a), by just generating a `~/.docker/config.json` with an access token directly, which has the benefit of not needing any cred helpers to work.
