### ISSUE TITLE
Firebase app hosting NextJs build fails when `NODE_ENV` is set to production in `apphosting.yaml` file

### ISSUE THREAD

**Issue by ashishmahla** [GoogleCloudPlatform/buildpacks#414]
**Describe the bug**
Deployment of NextJs app on firebase app hosting fails when `NODE_ENV` is set to production in the `apphosting.yaml` file and availability is set to BUILD as follows:

```
  - variable: NODE_ENV
    value: "production"
```

When setting NODE_ENV availability to RUNTIME, it builds successfully:
```
  - variable: NODE_ENV
    value: "production"
    availability:
      - RUNTIME
```

**Additional context**
How are you using GCP buildpacks?
I am using Firebase app hosting, so cloud build I think.

**What language is your project primarily written in?**
Node.js

**Steps To Reproduce**
Set NODE_ENV=production in `apphosting.yaml` file as follows:
```
  - variable: NODE_ENV
    value: "production"
```

**Error Logs**
```
Step #2: Module not found: Can't resolve '@/app/components/link'
Step #2:
Step #2: https://nextjs.org/docs/messages/module-not-found
Step #2:
Step #2:
Step #2: > Build failed because of webpack errors
Step #2: node:internal/modules/run_main:115
Step #2: triggerUncaughtException(
Step #2: ^
Step #2:
Step #2: [Error: ENOENT: no such file or directory, lstat '/workspace/.next/standalone'] {
Step #2: errno: -2,
Step #2: code: 'ENOENT',
Step #2: syscall: 'lstat',
Step #2: path: '/workspace/.next/standalone'
Step #2: }
Step #2:
Step #2: Node.js v22.2.0
Step #2: --------------------------------------------------------------------------------
Step #2: Sorry your project couldn't be built.
Step #2: Our documentation explains ways to configure Buildpacks to better recognise your project:
Step #2: -> https://cloud.google.com/docs/buildpacks/overview
Step #2: If you think you've found an issue, please report it:
Step #2: -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
Step #2: --------------------------------------------------------------------------------
```

I am unsure whether this is expected behaviour or not. I would like to apologise in advance, I don't primarily work with Node.js or Webpack.

**Comment by abhis3** [comment]
Hi there, would it be possible to share the code you're deploying? It would be great to take a look at your use case and debug it further if possible, thanks!

**Comment by abhis3** [comment]
I think the issues here have been ironed out, I was able to successfully deploy my sample app with a `NODE_ENV` value set to both `production` and `development`, see https://github.com/abhis3/express-on-firebase/blob/856e645d040ebd31d52062e3aca9a5140e620be8/apphosting.yaml#L12-L13

Closing out, please feel free to reopen if there are any other issues thanks!

**Comment by Jacquesjh** [comment]
This problem still happens if you use a secret and set it as "production" like this:

`  - variable: NODE_ENV
    secret: NodeEnv
`


Where you set the secret like this:
`firebase apphosting:secrets:set NodeEnv`
with the value "production"
