### ISSUE TITLE
App Hosting failed with yarn - Next JS

### ISSUE THREAD

**Issue by e-roy** [GoogleCloudPlatform/buildpacks#425]
**Describe the bug**
Using the Next.js boilerplate from [https://github.com/FirebaseExtended/firebase-framework-tools/tree/main/starters/nextjs/basic](https://github.com/FirebaseExtended/firebase-framework-tools/tree/main/starters/nextjs/basic), I deployed as is and worked fine.  If I remove `package-lock.json` file and use the yarn package manager, when I push to the same repo, build fails.

![app-hosting-fail](https://github.com/GoogleCloudPlatform/buildpacks/assets/70700747/68c67ac9-3e81-409c-9bd9-14aa252467ab)

Repo can be found at [https://github.com/e-roy/app-hosting-next-demo](https://github.com/e-roy/app-hosting-next-demo)

Error appears to be thrown in this file [https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/nodejs/firebasenextjs/main.go](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/nodejs/firebasenextjs/main.go)

**Comment by e-roy** [comment]
Consider also `pnpm`, I tested with another project and failed with the error below.  `pnpm` is popular among the Next JS crowd.



![pnpm](https://github.com/GoogleCloudPlatform/buildpacks/assets/70700747/a90d5922-c176-4e1a-8b5c-98629f577882)

**Comment by abhis3** [comment]
Hi there, thanks for the info in helping track this bug down! I just merged a fix here https://github.com/GoogleCloudPlatform/buildpacks/commit/f335a79a013cef72a96e94ee482e1a6705bfbcf9

I'll leave a comment again when it propagates through our service and the commit is in prod before closing this out.

**Comment by abhis3** [comment]
This change should be in all production servers now! Going to close this out, but please feel free to reopen if there are still issues!
