### ISSUE TITLE
React / App Hosting fails to deploy

### ISSUE THREAD

**Issue by pitchspace** [GoogleCloudPlatform/buildpacks#433]
**Describe the bug**
Please provide a  clear and concise description of what the bug is.

Fails to build, says next isn't found from App Hosting / Firebase. No dependency changes or critical code was changed, just CSS, etc., and the build failed 3 days later. Getting an error that worksapces/.next/standalone isn't available (more below). App Hosting on Firebase automatically builds when git is updated, so I've not changed the build, etc. Nominal code changes between 16th - 19th of July 2024 shouldn't have caused this. It was one line of CSS. Stumped here as to what changed.

If you have a general question about how to use buildpacks, we encourage you to open a [discussion topic instead](https://github.com/GoogleCloudPlatform/buildpacks/discussions)

**Additional context**
How are you using GCP buildpacks?
- [ ] `pack` and the `gcr.io/buildpacks/builder`
- [ ] Cloud Functions
- [ ] Cloud Run
- [X] Cloud Build
- [ ] App Engine Standard
- [ ] App Engine Flex

**Did this used to work?**
Yes

Was this working before? When did you start noticing these errors?
Was working fine on July 16, 2024. Updated two lines of CSS or so and it failed on the 19th.

**What language is your project primarily written in?**

React / Next

**Steps To Reproduce**

Pushed to git "git push origin main" to trigger "App Hosting" build, then fails

**Expected behavior**

Should Build successfully and deploy with a successful rollout, no errors. Dozens or previous builds worked fine in quick succession.

**Actual behavior**
What actually happened?

Step #2: > next build
2024-07-19 02:41:45.145 CST
Step #2: 
2024-07-19 02:41:45.145 CST
Step #2: sh: 1: next: not found
2024-07-19 02:41:45.145 CST
Step #2: node:internal/modules/run_main:115
2024-07-19 02:41:45.145 CST
Step #2:     triggerUncaughtException(
2024-07-19 02:41:45.145 CST
Step #2:     ^
2024-07-19 02:41:45.145 CST
Step #2: 
2024-07-19 02:41:45.145 CST
Step #2: [Error: ENOENT: no such file or directory, lstat '/workspace/.next/standalone'] {
2024-07-19 02:41:45.145 CST
Step #2:   errno: -2,
2024-07-19 02:41:45.145 CST
Step #2:   code: 'ENOENT',
2024-07-19 02:41:45.145 CST
Step #2:   syscall: 'lstat',
2024-07-19 02:41:45.145 CST
Step #2:   path: '/workspace/.next/standalone'
2024-07-19 02:41:45.145 CST
Step #2: }

- These files weren't touched, no build was reconstructed, and no permissions changed on the account between builds. Went and re-ran an old build as well, still didn't work. 

If applicable, add screenshots / logs / error messages

Consistently getting: error ID: d0a693a9

**Comment by jahjahbin** [comment]
Hey, apologies for the trouble. Could you give it another try on Mon/Tues? On 7/19 evening PDT, we finished changes to address #432 , so I'm wondering if that helped (or caused more issues).

**Comment by jahjahbin** [comment]
Excellent, thanks for reporting the issue. Feel free to reopen if you see more showstoppers.

**Comment by llwire** [comment]
I started seeing this issue today for a NextJS build. Any workarounds?

**Comment by 0iver** [comment]
I've also seen this issue recently, everything was working fine but in the last few days it's encountering this error. Deploy to Firebase Hosting on merge / build_and_deploy (push) is successful with no issues. If you need any logs more than happy to provide. Thanks!

**Comment by reloaddev** [comment]
Same problem here ):

**Comment by Chasusa** [comment]
Also experiencing the same issue :-(

**Comment by alexanderwanyoike** [comment]
Same here

**Comment by llwire** [comment]
Hey Folks, I believe I've found the issue and I've described it [here](https://github.com/GoogleCloudPlatform/buildpacks/issues/440).

Please check your build logs to confirm if your issues are the same as what I've described. If so, comment on the new issue to raise its visibility!
