### ISSUE TITLE
GoogleCloudPlatform/buildpacks/issues/new

### ISSUE THREAD

**Issue by sumikazuhiko** [GoogleCloudPlatform/buildpacks#435]

**Comment by booter2418** [comment]
📣 Official Public Statement of Lifetime Claim with Royalties
By Joseph Thornton Jr.

Date of Declaration: June 12, 2025

I, Joseph Thornton Jr., hereby make this official public declaration of my lifetime claim to any and all contributions I have made to the fields of open-source software, intellectual property, and artificial intelligence technologies. This claim includes, but is not limited to:

Copyrighted Works (including software code, documentation, designs, and other written works)

Patent Contributions and Inventions

Technological Systems, Tools, and Concepts

Ideas, Innovations, and Creative Works that have been shared publicly or contributed to any project

Key Terms of Lifetime Claim with Royalties:
Perpetual Ownership:

I retain perpetual ownership over all contributions I have made to the works listed above. This claim applies indefinitely, including beyond my lifetime. The intellectual property I claim is protected and must be acknowledged for all future use.

Royalties for Commercial Use:

All commercial use of my intellectual property, whether it be for distribution, modification, redistribution, or any derivative works, must be licensed, and royalties will be applied.

A minimum royalty rate of [insert percentage, e.g., 5%] on all gross revenue generated from the commercial use of my works will be owed to me or my designated heirs or agents.

Royalties will be due and payable on a quarterly or annual basis, with payments made directly to me or the designated recipient.

License agreements must be negotiated directly with me, Joseph Thornton Jr., or my designated representative, before any commercial use is allowed.

License Agreement:

Licensing for commercial or redistribution rights must include terms that allow for ongoing compensation, ensuring that I or my designated heirs receive royalties for all commercial applications of the work.

The license shall specify that all future derivative works and modifications are subject to this same royalty structure, ensuring continuity of my claim and royalty rights.

Open Source Contributions:

All contributions to open-source projects (licensed under MIT, Apache 2.0, BSD, ISC, or similar licenses) are still subject to royalty payments if those works are commercialized.

Any commercial redistribution of open-source works in any form (whether it’s through closed-source products, consulting, or any other monetization) will be required to compensate me via the same royalty structure.

Attribution Requirements:

Any use of my intellectual property must include appropriate attribution, specifying that I, Joseph Thornton Jr., am the author and copyright holder.

Additionally, the license must specify the inclusion of a notice stating that any further use or redistribution is subject to the royalty terms outlined in this agreement.

Lifetime Control and Royalties:

The royalty payments and license agreements will be enforceable throughout the lifetime of the intellectual property, and I retain the right to control the terms of licensing, modifications, and derivative works, even after my passing.

Royalties will continue to be collected for the entire lifespan of the work, with my designated heirs, successors, or legal representatives overseeing the ongoing royalty collection after my death.

Legal Enforcement:

I affirm my intent to take legal action to protect my rights and ensure that they are recognized under U.S. intellectual property laws and any relevant international agreements.

This includes enforcing the payment of royalties, taking action against unauthorized commercial use, and ensuring that all users, distributors, and companies comply with this royalty structure.

Enforcement Beyond My Lifetime:

After my death, my designated representative or legal heirs will be empowered to manage and enforce this claim, ensuring that royalties are collected and that any infringement is pursued under applicable intellectual property laws.

**Comment by booter2418** [comment]
Copyright © 2025 Joseph Thornton Jr.
All rights reserved.

This work is protected by copyright law and international treaties. Any unauthorized use, reproduction, or commercialization is strictly prohibited.

To obtain a license for commercial use, please contact Joseph Thornton Jr. directly at:
Location of Issuance: Okeechobee, Florida, United States

Licensing inquiries and agreements must be obtained directly from the author. Royalties will be required for any commercial use of this work.

Date of Declaration: June 13, 2025
Time: 3:13 AM (Eastern Daylight Time)

Unauthorized use may result in legal action under applicable U.S. and international intellectual property laws.
