### ISSUE TITLE
App Hosting build breaks when adding GenKit

### ISSUE THREAD

**Issue by dorraba** [GoogleCloudPlatform/buildpacks#442]
I have a nextjs app running on the app hosting
It builds and everything is fine
But when I use `firebase init` to add GenKit, and push the changes, the next build fails

<img width="1063" alt="image" src="https://github.com/user-attachments/assets/91165d50-3bdb-42aa-99e4-f2603295e10f">

**Comment by jama22** [comment]
@dorraba  I suggest opening an issue through official Firebase support channels https://firebase.google.com/support 

Alternatively, you can search through Firebase Tools GH to see if there is any issue matching yours https://github.com/firebase/firebase-tools
