### ISSUE TITLE
i need hepl for my firebase apphosting 

### ISSUE THREAD

**Issue by ncincd** [GoogleCloudPlatform/buildpacks#446]
2024-08-13 10:14:46.391 WAT
Step #2: 
2024-08-13 10:14:46.391 WAT
Step #2: Node.js v20.16.0
2024-08-13 10:14:46.391 WAT
Step #2: --------------------------------------------------------------------------------
2024-08-13 10:14:46.391 WAT
Step #2: Sorry your project couldn't be built.
2024-08-13 10:14:46.391 WAT
Step #2: Our documentation explains ways to configure Buildpacks to better recognise your project:
2024-08-13 10:14:46.391 WAT
Step #2:  -> https://cloud.google.com/docs/buildpacks/overview
2024-08-13 10:14:46.391 WAT
Step #2: If you think you've found an issue, please report it:
2024-08-13 10:14:46.391 WAT
Step #2:  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
2024-08-13 10:14:46.391 WAT
Step #2: --------------------------------------------------------------------------------
2024-08-13 10:14:46.393 WAT
Step #2: Timer: Builder ran for 41.300212386s and ended at 2024-08-13T09:14:46Z
2024-08-13 10:14:46.393 WAT
Step #2: ERROR: failed to build: exit status 1

**Comment by jama22** [comment]
@ncincd this project is for issues related to the GCP's buildpacks projects. If you need help with Firebase, please use the Firebase Support channels https://firebase.google.com/support
