### ISSUE TITLE
Failed to pull builder image

### ISSUE THREAD

**Issue by shaikatzz** [GoogleCloudPlatform/buildpacks#454]
**Describe the bug**
Please provide a  clear and concise description of what the bug is.

If you have a general question about how to use buildpacks, we encourage you to open a [discussion topic instead](https://github.com/GoogleCloudPlatform/buildpacks/discussions)

**Additional context**
How are you using GCP buildpacks?
- [x] `pack` and the `gcr.io/buildpacks/builder`

**Did this used to work?**
*(Yes/No)*
Yes, started to fail 5 hours ago

**What language is your project primarily written in?**
*(Python/Java/Node.js/Go/etc.)*
All

```
ERROR: validating that builder 'gcr.io/buildpacks/builder:google-22' exists: failed to inspect remote image 'gcr.io/buildpacks/builder:google-22': fetching builder image: connect to repo store "gcr.io/buildpacks/builder:google-22": GET https://gcr.io/v2/token?scope=repository%3Abuildpacks%2Fbuilder%3Apull&service=gcr.io: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/buildpacks/locations/us/repositories/gcr.io" (or it may not exist)
```

**Comment by shaikatzz** [comment]
After some retries the image was pulled and the following error was received: 
```
ERROR: failed to build: invalid run-image 'gcr.io/buildpacks/google-22/run': image 'gcr.io/buildpacks/google-22/run' does not exist in registry: not found
```

**Comment by kennethye1** [comment]
Sorry about that, we are migrating from GCR to AR and some permissions were not migrated. This should be fixed now.
