### ISSUE TITLE
`Unrecognized option: --add-opens` with Java 8

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/buildpacks#54]
The `--add-opens` flag was recently added to every Maven build. It seems to fail with Java 8. cc @eamonnmcmanus

**Comment by eamonnmcmanus** [comment]
I will look into this.

**Comment by briandealwis** [comment]
Workaround is to add a `.mvn/jvm.config`.

**Comment by eamonnmcmanus** [comment]
This should be fixed now. If `GOOGLE_RUNTIME_VERSION=8` then we don't apply `--add-opens`.

**Comment by briandealwis** [comment]
Fixed by 196a68e20e2a56ce998a9bc729ca292dbc6caf47
