### ISSUE TITLE
Multiple .NET Core project files support

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/buildpacks#61]
Hi, I am new to the buildpack world and I am trying to pack a ServiceStack API. A ServiceStack API consists of 3 projects in 1 solution.

I tried packing this (on Windows) 2 different ways:

1. I ran pack in the folder with the .sln file and this was the result:
`Failure: (ID: 5057fa43) expected to find exactly one project file in directory ., found [./test.Tests/test.Tests.csproj ./test.ServiceModel/test.ServiceModel.csproj ./test.ServiceInterface/test.ServiceInterface.csproj ./test/test.csproj]`

2. I ran pack in the main .csproj folder and it failed to find the others:
```
  Skipping project "/test.ServiceInterface/test.ServiceInterface.csproj" because it was not found.
  Skipping project "/test.ServiceModel/test.ServiceModel.csproj" because it was not found.
```

Can you provide some guidance on the correct way to pack this? I attached the project if you want to try it. I suspect I am missing something really simple.😬
[test.zip](https://github.com/GoogleCloudPlatform/buildpacks/files/4907943/test.zip)

**Comment by hdp617** [comment]
You can run pack in the folder with the .sln and set the `GOOGLE_BUILDABLE` env var to be the path to the project to be built e.g. `GOOGLE_BUILDABLE=test.ServiceModel`.

**Comment by EatonZ** [comment]
@hdp617 Figured it was something simple. That did the trick, thank you!😁
