### ISSUE TITLE
add an option to install os packages (for python)

### ISSUE THREAD

**Issue by vchrisb** [GoogleCloudPlatform/buildpacks#63]
Many python packages have dependencies to os packages. Like `django` is dependent on `gdal-bin` for handling gis data.
I think the current approach is to create my own run buildpack, based on `gcr.io/buildpacks/gcp/run:v1`.

```
FROM gcr.io/buildpacks/gcp/run:v1
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
  gdal-bin && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
USER cnb
```

Creating and maintaining my own run image, just to install an os package, is rather tedious. 

It would be great to add an option to specify a list of os packages to be installed.

**Comment by di** [comment]
If you need to customize the base image like this, you might be better off defining and building from your own `Dockerfile` instead. What advantage are you hoping to get by using `pack` and the GCP buildpacks here?

**Comment by jamesward** [comment]
There is a buildpack proposal for this functionality: https://github.com/buildpacks/rfcs/pull/87

**Comment by vchrisb** [comment]
@di I would loose all the benefits of buildpacks and its ecosystem. And I would need to maintain an image, all of that just because of one os dependency. 
Thx @jamesward https://github.com/buildpacks/rfcs/blob/app-mixins/text/0000-app-mixins.md#example-apt-buildpack is what I'm looking forward to.
