### ISSUE TITLE
Non-web Procfile Support

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/buildpacks#64]
With Heroku's `Procfile` support in their buildpacks, multiple processes can be defined, like:
```
web: start.sh
other: other.sh
```

The default process for the container is `web` but other processes can be run by specifying them as args, i.e.
`docker run gcr.io/asdf/zxcv other`

It seems that our `Procfile` support doesn't work with the non-web processes.  It'd be great to have this for compat with Heroku.

**Comment by di** [comment]
+1. My use case for this would be defining a `test` process that can run some tests within a built image.
