### ISSUE TITLE
Stack run.Dockerfile default ENV PORT overrides buildpack's env.launch defaults

### ISSUE THREAD

**Issue by vindvaki** [GoogleCloudPlatform/buildpacks#70]
### Problem

It looks like the `google` CNB stack sets a [default `PORT=8080` in its Dockerfile](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/builders/gcp/base/stack/run.Dockerfile). Running `docker inspect` on an image similarly shows that `Config.Env` has `PORT=8080`.

This makes it difficult to customize the *default* value of `PORT` at runtime, presumably because it gets set before the defaults in e.g.

- a custom buildpack's [`launch.env/PORT.default`](https://github.com/buildpacks/spec/blob/main/buildpack.md#default) 
- the [app's `.profile`](https://github.com/buildpacks/spec/blob/main/buildpack.md#app-interface)

are considered.

### Example: `.profile`

If I have a `.profile` with

```
export PORT=${PORT:-5000}
```

then the runtime value will remain at `8080`, but 

```
export PORT=5000
```

overrides the value.

### Example: `launch.env/PORT.default`

Say I have a custom buildpack at `$custom_buildpack_path` with a trivial `bin/detect`, and following `bin/build` and `buildpack.toml`, respectively

```bash
# bin/build

LAYER_DIR="$1/override-port"
ENV_DIR="$LAYER_DIR/env.launch"
mkdir -p "$ENV_DIR"
echo -n 5000 > "$ENV_DIR/PORT.default"
echo "launch = true" > "$LAYER_DIR.toml"
```

```toml
# buildpack.toml

api = "0.2"

[buildpack]
id = "com.example"
name = "Set a default runtime PORT environment variable"
version = "0.0.1"

[[stacks]]
id="google"
```

and prepend the custom buildpack google's set of buildpack

```bash
pack build test-default-port \
  --builder gcr.io/buildpacks/builder:v1 \
  --buildpack $custom_buildpack_path \
  --buildpack from=builder
```

then

```bash
docker run -it --rm test-default-port 'sh -c "echo $PORT"'
```

outputs `8080` as opposed to `5000`.

Contrast that to an image built with `gcr.io/paketo-buildpacks/builder:base`, where the `docker run` command outputs `5000`.

### Proposal

Get rid of `run.Dockerfile` and use `<layers>/<layer>/env` or `<layers>/<layer>/env.launch` instead.

**Comment by matthewrobertson** [comment]
I don't think this is bug. Your env var isn't getting set when you `docker run` because you are bypassing the buildpack launcher: https://buildpacks.io/docs/app-developer-guide/run-an-app/#no-launcher

I suspect if you did this it would work:

```
docker run --rm --entrypoint launcher test-default-port -- sh -c "echo $PORT"
```
