### ISSUE TITLE
Builder scaffolding - using this repo as a base for new builder collections

### ISSUE THREAD

**Issue by marcusmaday** [GoogleCloudPlatform/buildpacks#72]
Greetings!  I'm starting to create my own opinionated collection of builders (not GCP related).  I love the structure of this repo and am planning to use it as the base for my new collection.  Is there any appetite for publishing this repo as a pattern for the buildpack community as a whole to leverage?  I greatly prefer the pattern contained in this repository to the less cohesive one established by Cloud Foundry and Heroku.

**Comment by briandealwis** [comment]
Please feel free to fork or copy the repo, but this codebase is a mirror of our internal codebase, so we have to be very careful in how we change and update Bazel/Blaze configurations.  I plan to make some changes to support #73.

**Comment by marcusmaday** [comment]
Fair enough.  Thanks for the response!
