### ISSUE TITLE
App engine uses `npm ci` with `NODE_ENV=production` by default

### ISSUE THREAD

**Issue by fiws** [GoogleCloudPlatform/buildpacks#75]
It seems that the gae image switched to `npm ci` with `NODE_ENV=production` by default at some point.

This does not install the dev dependencies which breaks a lot of projects i think.

i could not find a way to change this. setting the `NODE_ENV` in the app.yaml does not work for the build step.

```
Step #5 - "builder": Running "npm ci --quiet (NODE_ENV=production)"
Step #5 - "builder": 
Step #5 - "builder": > sharp@0.26.0 install /workspace/node_modules/sharp
Step #5 - "builder": > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Step #5 - "builder": 
Step #5 - "builder": info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
Step #5 - "builder": 
Step #5 - "builder": > test-project@0.0.9 prepare /workspace
Step #5 - "builder": > tsc
Step #5 - "builder": 
Step #5 - "builder": sh: 1: tsc: not found
```

**Comment by lukasberger** [comment]
That you for the feedback. This change was made intentionally as including devDependencies in a production image is often undesirable.

To run a script that depends on devDependencies at build time, you can use the `gcp-build` script ([documentation](http://cloud/appengine/docs/standard/nodejs/running-custom-build-step)).

To override the default behavior of using `NODE_ENV=production` during installation, you can also create an `.npmrc` file in the root of your project with:

```
production = false
```

**Comment by fiws** [comment]
thanks for the feedback. but could you check the documentation link? it's invalid

**Comment by lukasberger** [comment]
Sorry, fixed.

**Comment by fiws** [comment]
thanks i fixed my problem with this. (a "we might break your code with this" email would have been nice tho imo :wink: )

**Comment by jaggervlad** [comment]
I have the same problem

Still not working :( Help!

**Comment by elyobo** [comment]
Opposite problem, in spite of no attempt to override defaults we're seeing app engine run NODE_ENV development, install dev dependencies, and then run `npm run build` (which fails, because we don't even deploy the code required to do that, just the already built assets).

**Comment by alexnault** [comment]
@elyobo We have the same issue.

We've started seeing `GOOGLE_EXPERIMENTAL_NODEJS_NPM_BUILD_ENABLED` yesterday. Since then, Cloud Build w/ GAE has started running with NODE_ENV=development, which is unwanted.

**Comment by johnnyoshika** [comment]
Interestingly this problem only appeared when deploying to `northamerica-northeast1` region. In `us-central1` it wasn't a problem for me, although this could change in the future.

To fix this when deploying cloud functions, I set this during `gcloud functions deploy`:

```
--set-build-env-vars GOOGLE_NODE_RUN_SCRIPTS=
```

A similar problem appeared when deploying Firebase Functions (also only in `northamerica-northeast1` ). The fix was to upgrade `firebase-tools` from version `11.20.0` to `11.28.0`.
