### ISSUE TITLE
Feature Request: Java 15

### ISSUE THREAD

**Issue by adamzr** [GoogleCloudPlatform/buildpacks#78]
I'm interested in using the buildpacks, but we use the latest version of Java, currently Java 15. The docs state you only support the LTS version (Java 11). Can you add support for the current latest stable version of Java (i.e. 15)?

**Comment by lukasberger** [comment]
Even though the README does not indicate so, Java 15 should already work if you pass in `-e GOOGLE_RUNTIME_VERSION=15` at build time.

**Comment by adamzr** [comment]
This works, thanks!
