### ISSUE TITLE
Update google.python.pip Version

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/buildpacks#80]
The pip version used to install packages with GCF is outdated. It should be 19+ in order to install packages like tensorflow in GCF.

I believe the source for the pip version is:

https://github.com/GoogleCloudPlatform/buildpacks/blob/main/cmd/python/pip/buildpack.toml

It should be 19+.

B: b/145374253
CC: @lukasberger @di 
See internal doc: Google Cloud Buildpacks + Python – Friction

**Comment by di** [comment]
Are you referring to this line? https://github.com/GoogleCloudPlatform/buildpacks/blob/77ff79fc4b91051efd0c2c721e1476c306a847f2/cmd/python/pip/buildpack.toml#L5

This is the buildpack version, not the `pip` version. The GCF buildpack currently uses `pip==20.2.3`, the latest version.

**Comment by lukasberger** [comment]
Dustin's right, that's the buildpack version. The bug is from last year.
