### ISSUE TITLE
Launcher Override Via Args

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/buildpacks#82]
I believe it used to work to override a launcher command by doing something like:
```
docker run -it foo "/foo blah"
```

But that doesn't seem to be the case anymore.  Now it always just runs what is in the `Procfile`.

Here is an example: https://github.com/GoogleCloudPlatform/kotlin-samples/tree/broken-proc/run/grpc-hello-world-gradle

Note how the default `web` process is to run the server, but it used to work to run the client with the args.

**Comment by lukasberger** [comment]
Yes, it did, but lifecycle changed this behavior in version 0.9.0 [release notes](https://github.com/buildpacks/lifecycle/releases/tag/v0.9.0). The relevant RFC is [RFC-0045](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md).

Lifecycle now writes all processes to `/cnb/processes`, which is added to PATH and removed before the chosen process is launched. The way to run custom processes is using `docker --entrypoint=<foo>`, where <foo> is either a process contributed by a buildpack or any other binary on PATH, e.g. `--entrypoint=web`, `--entrypoint=/bin/bash`, etc.

**Comment by lukasberger** [comment]
I think the changes made in the linked PR were the correct thing to do based on some [examples](https://github.com/buildpacks/rfcs/blob/main/text/0045-launcher-arguments.md#specifying-a-custom-process-at-runtime) in the RFC.

**Comment by jamesward** [comment]
Ah! Thanks. I was able to make this work with `--entrypoint=/cnb/lifecycle/launcher` but can't do non-web `Procfile` named processes due to: https://github.com/GoogleCloudPlatform/buildpacks/issues/64

**Comment by di** [comment]
For posterity, the full command is: `docker run --entrypoint=<entrpoint> -i <image>`, and this now works with non-web `Procfile` named processes.
