### ISSUE TITLE
Broken go cloud function builds

### ISSUE THREAD

**Issue by ottob** [GoogleCloudPlatform/buildpacks#84]
Hello, [this commit ](https://github.com/census-instrumentation/opencensus-go/commit/fc3822be251c0e5c0d1b92bd51fabe401fe3c0bf) to `opencensus-go` seems to have broken go Google Cloud Function deploys for me. I understand that this is is probably not the correct place to report this but it was the best place I could find.

I started getting this error today when Im trying to deploy go cloud functions. Ive tried multiple regions and projects, always with the same error.

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: # github.com/cloudevents/sdk-go/v2/extensions
src/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go:161:3: cannot use span (type trace.Span) as type *trace.Span in return argument:
	*trace.Span is pointer to interface, not interface; Error ID: 1093f764
```

From the stack driver logs:
```
Step #4 - "builder": go version go1.13.12 linux/amd64
Step #4 - "builder": Done "go version" (4.124119ms)
Step #4 - "builder": Running "go get github.com/GoogleCloudPlatform/functions-framework-go/funcframework (GOPATH=/workspace GOCACHE=/tmp/serverless_function_app170363466)"
Step #4 - "builder": # github.com/cloudevents/sdk-go/v2/extensions
Step #4 - "builder": src/github.com/cloudevents/sdk-go/v2/extensions/distributed_tracing_extension.go:161:3: cannot use span (type trace.Span) as type *trace.Span in return argument:
```

Shouldn't the build pack used pinned versions of these dependencies instead of using master version?

**Comment by ottob** [comment]
Im building using a `vendor` folder since I have private dependencies. I have deployed the same code previously without any issues.

**Comment by Jofre** [comment]
Related: https://status.cloud.google.com/incident/cloud-functions/20006

**Comment by ottob** [comment]
And: https://github.com/GoogleCloudPlatform/functions-framework-go/issues/56
