### ISSUE TITLE
Improve .NET version support/configuration

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/buildpacks#89]
Hi, can you add .NET 5 recognition? Even with the project file set up with `<TargetFramework>net5.0</TargetFramework>`, it still attempts to download v3.1.404.

The error message mentions I should override `GOOGLE_RUNTIME_VERSION`, but that's not preferable since I would need to keep track of it and update it on a (probably) weekly or monthly basis.

**Comment by EatonZ** [comment]
@lukasberger Have you given any thought to this yet? If you want to keep .NET Core 3.1 LTS the default, perhaps a new option, such as `GOOGLE_USE_LTS`, can be introduced so people can signal they want to use the latest, non-LTS .NET versions. .NET Core 3.1 is LTS and .NET 5 is not. .NET 6 will be LTS though - they are LTS'ing every other release.

**Comment by meteatamel** [comment]
I agree. If the project has `net5.0`, the buildpack should attempt to use 5.0..Most new .NET projects are now using 5.0 and it really limits the usefulness of buildpacks for .NET.

**Comment by EatonZ** [comment]
@meteatamel Once .NET 6 comes out, that will become the new default for buildpacks since it will be LTS.
Once .NET 7 comes around a year later, this same problem will occur, so it makes the most sense to have an option to specify whether to use the LTS version or not.

**Comment by EatonZ** [comment]
@meteatamel @lukasberger I was preparing my .NET 6 publish today and I was surprised to learn my above assumption was wrong. It appears the version is now pinned to 3.1 in [this commit](https://github.com/GoogleCloudPlatform/buildpacks/commit/48fa59de7c42e13e99b156ed5112076286cf2a1b#diff-8879102bbe7483ae7a49c9b4a0efc5b62553b24ce9a4b307f45e0fccd614c5fb).

@spew Can you answer 2 questions?
1. Why is .NET 6 broken as indicated by [your comment](https://github.com/GoogleCloudPlatform/buildpacks/blob/4b2218995b5881bd7893addef36824c39af17d2d/pkg/dotnet/release/client/client.go#L28)?
2. Will your changes essentially solve this issue? I would highly suggest adding some `USE_LTS` flag like I mentioned above so deployments can be done using .NET 7 later this year (since that one won't be LTS).

**Comment by meteatamel** [comment]
I guess the bigger question for the buildpacks team is whether the buildpack only supports the LTS versions. My vote is to have it support all versions of .NET (not just LTS) because as @EatonZ points out, the buildpack will keep breaking, every time there's a non-LTS version. But I understand this is more work.

**Comment by spew** [comment]
The LTS version does not work at all due to the hacky way that we install the SDK and then 'delete' the SDK portion to only leave the runtime.

The fix I have in progress (sorry, code reviews have been taking a while) will support all versions of the core SDK, i.e. everything after dotnetcore1.0

**Comment by EatonZ** [comment]
Issue is now solved thanks to work from @spew.
[More information about the changes.](https://github.com/GoogleCloudPlatform/buildpacks/issues/157#issuecomment-1029408023)

**Comment by spew** [comment]
Fixed by https://github.com/GoogleCloudPlatform/buildpacks/issues/157
