### ISSUE TITLE
New registry URL

### ISSUE THREAD

**Issue by EatonZ** [GoogleCloudPlatform/buildpacks#90]
Hi, [Google Cloud Artifact Registry went GA today](https://cloud.google.com/blog/products/devops-sre/artifact-registry-is-ga).

[The readme](https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md) should be updated with the new `pkg.dev` domain (replacing `gcr.io`) whenever you start uploading to the new Artifact Registry.

**Comment by EatonZ** [comment]
Is anyone able to comment on when this may happen?

**Comment by lukasberger** [comment]
We don't have any concrete plans at the moment. Are there specific features you're looking for that GCR doesn't offer?

**Comment by EatonZ** [comment]
No, I just would like to know when it happens so I can update the domain in my code.🙂

**Comment by matthewrobertson** [comment]
We have no plans to switch to AR at this time. We will upload the README if we do
