### ISSUE TITLE
Integration of 3rd party buildpacks

### ISSUE THREAD

**Issue by mmanciop** [GoogleCloudPlatform/buildpacks#91]
At Instana we are working on a Cloud-Native buildpack, called instana buildpack, for CloudRun.

The instana buildpack itself is pretty straightforward (albeit not yet published) and we love that it entirely automates the task of adding the Instana collectors.

However, the user experience of having the instana buildpack not automatically considered by the builder is less than great: to our understanding, specifying one `--buildpack` to have the Instana buildpack used, overrides the detection phase of the default buildpacks in the builder, which forces a user to have to specify manually _all the other buildpacks to use_.

Is there a way to say to `pack` to please use a specific buildpack _in addition to_ anything else the builder already knows?

Other options like asking Instana customers to keep a builder fork, are frankly not a seamless UX and will result in confusion and support woes.

Any ideas?

**Comment by jamesward** [comment]
cc @jkutner

**Comment by jromero** [comment]
Hi @mmanciop,

A `pack` maintainer here. This is possible via an (apparently) undocumented option [`--buildpack from=builder`](https://github.com/buildpacks/pack/pull/450).

Some example commands:

> Buildpack `buildpacks/hello-processes` is APPENDED to each "order". Hence it uses the buildpacks from the builder.

```
pack build my-app --builder cnbs/sample-builder:bionic --buildpack from=builder --buildpack buildpacks/hello-processes
```

vs

> Buildpack `buildpacks/hello-processes` is PREPENDED to each "order". Hence it uses the buildpacks from the builder.

```
pack build my-app --builder cnbs/sample-builder:bionic --buildpack buildpacks/hello-processes --buildpack from=builder
```

_NOTE: Eventually this will [move to URIs](https://github.com/buildpacks/pack/issues/765)._

**Comment by mmanciop** [comment]
Oh, this is a great undocumented feature, thanks!
