### ISSUE TITLE
Fail to run TF.JS

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpacks#94]
I was trying to deploy [this sample](https://github.com/juandes/tf-js-examples/tree/main/node-od-service)

package.json:
```
{
    "name": "tfjs-node-toxicity-server",
    "version": "0.0.1",
    "description": "A server that exposes a Toxicity detection model",
    "scripts": {
        "start": "node index.js"
    },
    "dependencies": {
        "@tensorflow/tfjs-node": "^2.7.0",
        "@tensorflow-models/toxicity": "^1.2.2",
        "express": "^4.17.1"
    }
}
```
index.js
```
const tf = require('@tensorflow/tfjs-node');
const toxicity = require('@tensorflow-models/toxicity');
const express = require('express');

const threshold = 0.9;
const port = process.env.PORT || 8080;

async function runServer() {
  const model = await toxicity.load(threshold);
  const app = express();

  app.use(express.json());

  app.post('/prediction', (req, res) => {
    model.classify([req.body.sentence]).then((predictions) => {
      // Send the response to the user
      res.json({
        predictions,
      });
    });
  });

  app.listen(port, () => {
    console.log(`Listening on port ${port}`);
  });
}

runServer();
```

But when deployed to Cloud Run, I see this error at startup:
`"Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /workspace/node_modules/@tensorflow/tfjs-node/lib/napi-v6/tfjs_binding.node."`

This is not an error I get when I use this Dockerfile insteaf of GCP Buildpacks:
```

FROM node:15

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . ./

CMD [ "node", "index.js" ]
```

**Comment by pyu10055** [comment]
This could be related to the node and napi version of GCP buildpacks. can you provide the default node and napi versions?

**Comment by lukasberger** [comment]
It looks like the issue is that tensorflow requires Python to be available at compile time, but we don't include it with our builder image. For some reason `npm` does not emit any warnings, even in verbose mode. Interestingly, for Node.js 10, for which prebuilt binaries are not available, the logs contain a failure message from `node-gyp` about missing Python installation, but the install command exits with 0. When I remove `python.*` from the `node:15` image and run docker build, the built image exhibits the same behavior.

After extending the builder image with Python following the [instructions](https://github.com/GoogleCloudPlatform/buildpacks#extending-the-builder-image), the application builds and runs as expected.

**Comment by pyu10055** [comment]
someone created this docker file that seems to work:

```
FROM node:14-slim
WORKDIR /usr/src/app

RUN apt-get update -qqy && apt-get install -qqy \
        curl \
        gcc \
        python3-setuptools \
        python3-dev \
        python3-pip \
        apt-transport-https \
        lsb-release \
        openssh-client \
        git \
        gnupg && \
        rm -rf /var/lib/apt/lists/*
COPY package*.json ./
RUN npm install --only=production
COPY . ./
CMD [ "node", "index.js" ]
```

**Comment by ahmetb** [comment]
I copied that dockerfile from tf.js's own repo that's used to build tf.js itself. It's probably an overkill. I see tf.js has a fallback logic when python doesn't exist, but it 404s. See #96 logs.

**Comment by steren** [comment]
Over chat, we found it acceptable to add `python` to the builder image (not the runtime image), which would solve this issue, right?

**Comment by ahmetb** [comment]
Yes, it seems to be working without Python in the final image.

To test this, I made a new stage in the Dockerfile above and copied over the app directory with the populated `node_modules` after "npm install" to a clean image:

```diff
@@ -16,4 +16,8 @@ RUN apt-get update -qqy && apt-get install -qqy \
 COPY package*.json ./
 RUN npm install --only=production
 COPY . ./
+
+FROM node:14-slim
+COPY --from=0 /usr/src/app /usr/src/app
+WORKDIR /usr/src/app
 CMD [ "node", "index.js" ]
```

It reduces container image from 1.05GB to 637MB.
