### ISSUE TITLE
pack build fails ... maybe because of not excluding files like in cloud build using .cloudignore

### ISSUE THREAD

**Issue by picaoao** [GoogleCloudPlatform/buildpacks#95]
I'm able to deploy the function in google (cloud functions) but I can't build the container using pack.

Nevertheless to do the deploy in cloud I need to add a `.cloudignore`:

```
go.mod
go.sum
.git
.gitignore
*_test.go
```

... and I need to exclude `_test` files because they live in a different package and I need to exclude `go.mod` and `go.sum` and generate a `vendor` folder because I have private repositores and dependencies and there is no support for that.

However if I try to use pack to build locally a container, it fails. It seems it is for the same reason as it would fail in cloud.
It seems like it is because locally it is not ignoring the files like it doesn't in cloud build.

Is there any way of doing the same locally ??

Example output of error:

=== Go - Functions Framework (google.go.functions-framework@0.9.3) ===
--------------------------------------------------------------------------------
Running "go run main -dir /workspace/serverless_function_source_code (GOPATH=/cnb/buildpacks/google.go.functions-framework/0.9.3/converter/get_package GOCACHE=/tmp/serverless_function_app240907007)"
2020/12/15 16:37:36 Unable to extract package name: multiple packages in user code directory: webhook != webhook_test.
exit status 1
Done "go run main -dir /workspace/serverless_function_source_code ..." (451.399516ms)
Failure: (ID: aba1aa6a) 2020/12/15 16:37:36 Unable to extract package name: multiple packages in user code directory: webhook != webhook_test.
exit status 1

**Comment by lukasberger** [comment]
Support for `.gcloudignore` is implemented in the `gcloud` CLI and the exclusions happen at upload time outside of the buildpacks build context. If you're using `pack` to build the image locally, the way to specify exclusions would be using [`project.toml`](https://buildpacks.io/docs/app-developer-guide/using-project-descriptor), for example:

```
[build]
exclude = [
    "go.mod",
    "go.sum"
]
```

**Comment by picaoao** [comment]
It works ! Thanks for the help !
