### ISSUE TITLE
Evaluate if `Main-Class` in `Manifest.txt` can be used to determine Java entrypoint

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpacks#99]
See https://docs.oracle.com/javase/tutorial/deployment/jar/appman.html

It seems that there exist an additional idiomatic way to define the entrypoint of a Java app.

**Comment by steren** [comment]
CC @ludoch @glaforge

**Comment by ludoch** [comment]
Is it not done in:

https://github.com/GoogleCloudPlatform/buildpacks/blob/cb5b92639ded8fd161629cb3a1dc3d0fb00cc066/pkg/java/java.go#L45

// ExecutableJar looks for the jar with a Main-Class manifest. If there is not exactly 1 of these jars, throw an error.

**Comment by steren** [comment]
I assume you mean "now" instead of "not"?

If it's supported, please document it [here](https://github.com/GoogleCloudPlatform/buildpacks#language-specific-behavior)

**Comment by ludoch** [comment]
See https://github.com/GoogleCloudPlatform/buildpacks/blob/58e6045476f951cdada4423b86369eb6214b6002/README.md#language-specific-behavior

**Comment by steren** [comment]
Ah right it's already there.
